//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load assembly \&quot;{0}\&quot;..
        /// </summary>
        internal static string AssemblyLoadFailedException {
            get {
                return ResourceManager.GetString("AssemblyLoadFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be &gt; {0} characters..
        /// </summary>
        internal static string BCryptHashLengthOutOfRange {
            get {
                return ResourceManager.GetString("BCryptHashLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BCrypt work factor provided! Creating new hash using default work factor..
        /// </summary>
        internal static string BCryptHashWorkFactorOutOfRange {
            get {
                return ResourceManager.GetString("BCryptHashWorkFactorOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BCrypt work factor provided! Upgrading input to BCrypt using default work factor..
        /// </summary>
        internal static string BCryptHashWorkFactorOutOfRangeUpgrade {
            get {
                return ResourceManager.GetString("BCryptHashWorkFactorOutOfRangeUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Not upgrading work factor because bcrypt hash in an invalid format..
        /// </summary>
        internal static string BCryptInvalidHashFormat {
            get {
                return ResourceManager.GetString("BCryptInvalidHashFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BCrypt work factor provided! Refusing to change work-factor on exsting hash..
        /// </summary>
        internal static string BCryptInvalidWorkFactor {
            get {
                return ResourceManager.GetString("BCryptInvalidWorkFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config path has been set to {0}..
        /// </summary>
        internal static string ConfigPathCmdLineOutput {
            get {
                return ResourceManager.GetString("ConfigPathCmdLineOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing algorithm {0} is not supported..
        /// </summary>
        internal static string HashAlgoUnsupported {
            get {
                return ResourceManager.GetString("HashAlgoUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid storage type..
        /// </summary>
        internal static string InvalidDbTypeException {
            get {
                return ResourceManager.GetString("InvalidDbTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql not setup correctly..
        /// </summary>
        internal static string MySqlException {
            get {
                return ResourceManager.GetString("MySqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion plugin \&quot;{0}\&quot; has thrown an exception while being disposed: 
        ///{1}..
        /// </summary>
        internal static string PluginDisposedOutput {
            get {
                return ResourceManager.GetString("PluginDisposedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion plugin \&quot;{0}\&quot; is designed for a different Orion version ({1}) and was ignored..
        /// </summary>
        internal static string PluginIgnoredOutput {
            get {
                return ResourceManager.GetString("PluginIgnoredOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion plugin \&quot;{0}\&quot; has thrown an exception during initialization..
        /// </summary>
        internal static string PluginInitializeException {
            get {
                return ResourceManager.GetString("PluginInitializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of orion plugin class \&quot;{0}\&quot;..
        /// </summary>
        internal static string PluginInstanceFailedException {
            get {
                return ResourceManager.GetString("PluginInstanceFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion has successfully loaded the following plugins: 
        ///{0}.
        /// </summary>
        internal static string PluginsLoadedOutput {
            get {
                return ResourceManager.GetString("PluginsLoadedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save path has been set to {0}..
        /// </summary>
        internal static string SavePathCmdLineOutput {
            get {
                return ResourceManager.GetString("SavePathCmdLineOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group parameter must be a valid group name, group ID, or Group object.
        /// </summary>
        internal static string SetUserGroupException {
            get {
                return ResourceManager.GetString("SetUserGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided UserAccount was invalid.
        /// </summary>
        internal static string SetUserGroupInvalidAccountException {
            get {
                return ResourceManager.GetString("SetUserGroupInvalidAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided group ID was invalid.
        /// </summary>
        internal static string SetUserGroupInvalidIDException {
            get {
                return ResourceManager.GetString("SetUserGroupInvalidIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided group name was invalid.
        /// </summary>
        internal static string SetUserGroupInvalidNameException {
            get {
                return ResourceManager.GetString("SetUserGroupInvalidNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal startup exception..
        /// </summary>
        internal static string StartupException {
            get {
                return ResourceManager.GetString("StartupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to log as log has been disposed..
        /// </summary>
        internal static string TextLogDisposedOutput {
            get {
                return ResourceManager.GetString("TextLogDisposedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; already exists..
        /// </summary>
        internal static string UserCollision {
            get {
                return ResourceManager.GetString("UserCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments in UserHandler.SetParameters: password, group and uuid may not all be null..
        /// </summary>
        internal static string UserHandlerSetParameterInvalidArgs {
            get {
                return ResourceManager.GetString("UserHandlerSetParameterInvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserHandler.SetParameter returned an error for User ID {0}..
        /// </summary>
        internal static string UserHandlerSetParameterUserIDError {
            get {
                return ResourceManager.GetString("UserHandlerSetParameterUserIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID may not be less than 0..
        /// </summary>
        internal static string UserIDLessThanZero {
            get {
                return ResourceManager.GetString("UserIDLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
