//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load assembly \&quot;{0}\&quot;..
        /// </summary>
        internal static string AssemblyLoadFailedException {
            get {
                return ResourceManager.GetString("AssemblyLoadFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config path has been set to {0}.
        /// </summary>
        internal static string ConfigPathCmdLineOutput {
            get {
                return ResourceManager.GetString("ConfigPathCmdLineOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid storage type..
        /// </summary>
        internal static string InvalidDbTypeException {
            get {
                return ResourceManager.GetString("InvalidDbTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql not setup correctly..
        /// </summary>
        internal static string MySqlException {
            get {
                return ResourceManager.GetString("MySqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion plugin \&quot;{0}\&quot; has thrown an exception while being disposed:\n{1}.
        /// </summary>
        internal static string PluginDisposedOutput {
            get {
                return ResourceManager.GetString("PluginDisposedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion plugin \&quot;{0}\&quot; is designed for a different Orion version ({1}) and was ignored..
        /// </summary>
        internal static string PluginIgnoredOutput {
            get {
                return ResourceManager.GetString("PluginIgnoredOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion plugin \&quot;{0}\&quot; has thrown an exception during initialization..
        /// </summary>
        internal static string PluginInitializeException {
            get {
                return ResourceManager.GetString("PluginInitializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of orion plugin class \&quot;{0}\&quot;..
        /// </summary>
        internal static string PluginInstanceFailedException {
            get {
                return ResourceManager.GetString("PluginInstanceFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion has successfully loaded the following plugins: \n {\n    {0}\n }.
        /// </summary>
        internal static string PluginsLoadedOutput {
            get {
                return ResourceManager.GetString("PluginsLoadedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save path has been set to {0}.
        /// </summary>
        internal static string SavePathCmdLineOutput {
            get {
                return ResourceManager.GetString("SavePathCmdLineOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal startup exception..
        /// </summary>
        internal static string StartupException {
            get {
                return ResourceManager.GetString("StartupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to log as log has been disposed..
        /// </summary>
        internal static string TextLogDisposedOutput {
            get {
                return ResourceManager.GetString("TextLogDisposedOutput", resourceCulture);
            }
        }
    }
}
