using System;

namespace Orion.Npcs
{
	/// <summary>
	/// Specifies the type of an <see cref="INpc"/> instance.
	/// </summary>
	public struct NpcType : IEquatable<NpcType>
	{
#pragma warning disable 1591
		public static NpcType AncientCultistSquidhead => new NpcType(521);
		public static NpcType AncientDoom => new NpcType(523);
		public static NpcType AncientLight => new NpcType(522);
		public static NpcType Angler => new NpcType(369);
		public static NpcType AnglerFish => new NpcType(102);
		public static NpcType AngryBones => new NpcType(31);
		public static NpcType AngryBonesBig => new NpcType(294);
		public static NpcType AngryBonesBigHelmet => new NpcType(296);
		public static NpcType AngryBonesBigMuscle => new NpcType(295);
		public static NpcType AngryNimbus => new NpcType(250);
		public static NpcType AngryTrapper => new NpcType(175);
		public static NpcType AnomuraFungus => new NpcType(257);
		public static NpcType Antlion => new NpcType(69);
		public static NpcType Arapaima => new NpcType(157);
		public static NpcType ArmedZombie => new NpcType(430);
		public static NpcType ArmedZombieCenx => new NpcType(436);
		public static NpcType ArmedZombieEskimo => new NpcType(431);
		public static NpcType ArmedZombiePincussion => new NpcType(432);
		public static NpcType ArmedZombieSlimed => new NpcType(433);
		public static NpcType ArmedZombieSwamp => new NpcType(434);
		public static NpcType ArmedZombieTwiggy => new NpcType(435);
		public static NpcType ArmoredSkeleton => new NpcType(77);
		public static NpcType ArmoredViking => new NpcType(197);
		public static NpcType ArmsDealer => new NpcType(19);
		public static NpcType BabySlime => new NpcType(-5);
		public static NpcType BaldZombie => new NpcType(132);
		public static NpcType Bee => new NpcType(210);
		public static NpcType BeeSmall => new NpcType(211);
		public static NpcType BigBaldZombie => new NpcType(-29);
		public static NpcType BigBoned => new NpcType(-14);
		public static NpcType BigCrimera => new NpcType(-23);
		public static NpcType BigCrimslime => new NpcType(-25);
		public static NpcType BigEater => new NpcType(-12);
		public static NpcType BigFemaleZombie => new NpcType(-45);
		public static NpcType BigHeadacheSkeleton => new NpcType(-49);
		public static NpcType BigHornetFatty => new NpcType(-57);
		public static NpcType BigHornetHoney => new NpcType(-59);
		public static NpcType BigHornetLeafy => new NpcType(-61);
		public static NpcType BigHornetSpikey => new NpcType(-63);
		public static NpcType BigHornetStingy => new NpcType(-65);
		public static NpcType BigMimicCorruption => new NpcType(473);
		public static NpcType BigMimicCrimson => new NpcType(474);
		public static NpcType BigMimicHallow => new NpcType(475);
		public static NpcType BigMimicJungle => new NpcType(476);
		public static NpcType BigMisassembledSkeleton => new NpcType(-51);
		public static NpcType BigMossHornet => new NpcType(-20);
		public static NpcType BigPantlessSkeleton => new NpcType(-53);
		public static NpcType BigPincushionZombie => new NpcType(-31);
		public static NpcType BigRainZombie => new NpcType(-55);
		public static NpcType BigSkeleton => new NpcType(-47);
		public static NpcType BigSlimedZombie => new NpcType(-33);
		public static NpcType BigStinger => new NpcType(-17);
		public static NpcType BigSwampZombie => new NpcType(-35);
		public static NpcType BigTwiggyZombie => new NpcType(-37);
		public static NpcType BigZombie => new NpcType(-27);
		public static NpcType Bird => new NpcType(74);
		public static NpcType BirdBlue => new NpcType(297);
		public static NpcType BirdRed => new NpcType(298);
		public static NpcType BlackRecluse => new NpcType(163);
		public static NpcType BlackRecluseWall => new NpcType(238);
		public static NpcType BlackSlime => new NpcType(-6);
		public static NpcType BlazingWheel => new NpcType(72);
		public static NpcType BloodCrawler => new NpcType(239);
		public static NpcType BloodCrawlerWall => new NpcType(240);
		public static NpcType BloodFeeder => new NpcType(241);
		public static NpcType BloodJelly => new NpcType(242);
		public static NpcType BloodZombie => new NpcType(489);
		public static NpcType BlueArmoredBones => new NpcType(273);
		public static NpcType BlueArmoredBonesMace => new NpcType(274);
		public static NpcType BlueArmoredBonesNoPants => new NpcType(275);
		public static NpcType BlueArmoredBonesSword => new NpcType(276);
		public static NpcType BlueJellyfish => new NpcType(63);
		public static NpcType BlueSlime => new NpcType(1);
		public static NpcType BoneLee => new NpcType(287);
		public static NpcType BoneSerpentBody => new NpcType(40);
		public static NpcType BoneSerpentHead => new NpcType(39);
		public static NpcType BoneSerpentTail => new NpcType(41);
		public static NpcType BoneThrowingSkeleton => new NpcType(449);
		public static NpcType BoneThrowingSkeleton2 => new NpcType(450);
		public static NpcType BoneThrowingSkeleton3 => new NpcType(451);
		public static NpcType BoneThrowingSkeleton4 => new NpcType(452);
		public static NpcType BoundGoblin => new NpcType(105);
		public static NpcType BoundMechanic => new NpcType(123);
		public static NpcType BoundWizard => new NpcType(106);
		public static NpcType BrainofCthulhu => new NpcType(266);
		public static NpcType BrainScrambler => new NpcType(381);
		public static NpcType Buggy => new NpcType(487);
		public static NpcType Bunny => new NpcType(46);
		public static NpcType BunnySlimed => new NpcType(303);
		public static NpcType BunnyXmas => new NpcType(337);
		public static NpcType BurningSphere => new NpcType(25);
		public static NpcType Butcher => new NpcType(460);
		public static NpcType Butterfly => new NpcType(356);
		public static NpcType CataractEye => new NpcType(190);
		public static NpcType CataractEye2 => new NpcType(-38);
		public static NpcType CaveBat => new NpcType(49);
		public static NpcType ChaosBall => new NpcType(30);
		public static NpcType ChaosElemental => new NpcType(120);
		public static NpcType ChatteringTeethBomb => new NpcType(378);
		public static NpcType Clinger => new NpcType(101);
		public static NpcType Clothier => new NpcType(54);
		public static NpcType Clown => new NpcType(109);
		public static NpcType CochinealBeetle => new NpcType(217);
		public static NpcType CorruptBunny => new NpcType(47);
		public static NpcType CorruptGoldfish => new NpcType(57);
		public static NpcType Corruptor => new NpcType(94);
		public static NpcType CorruptPenguin => new NpcType(168);
		public static NpcType CorruptSlime => new NpcType(81);
		public static NpcType Crab => new NpcType(67);
		public static NpcType Crawdad => new NpcType(494);
		public static NpcType Crawdad2 => new NpcType(495);
		public static NpcType CreatureFromTheDeep => new NpcType(461);
		public static NpcType Creeper => new NpcType(267);
		public static NpcType Crimera => new NpcType(173);
		public static NpcType Crimslime => new NpcType(183);
		public static NpcType CrimsonAxe => new NpcType(179);
		public static NpcType CrimsonBunny => new NpcType(464);
		public static NpcType CrimsonGoldfish => new NpcType(465);
		public static NpcType CrimsonPenguin => new NpcType(470);
		public static NpcType CultistArcherBlue => new NpcType(379);
		public static NpcType CultistArcherWhite => new NpcType(380);
		public static NpcType CultistBoss => new NpcType(439);
		public static NpcType CultistBossClone => new NpcType(440);
		public static NpcType CultistDevote => new NpcType(438);
		public static NpcType CultistDragonBody1 => new NpcType(455);
		public static NpcType CultistDragonBody2 => new NpcType(456);
		public static NpcType CultistDragonBody3 => new NpcType(457);
		public static NpcType CultistDragonBody4 => new NpcType(458);
		public static NpcType CultistDragonHead => new NpcType(454);
		public static NpcType CultistDragonTail => new NpcType(459);
		public static NpcType CultistTablet => new NpcType(437);
		public static NpcType CursedHammer => new NpcType(83);
		public static NpcType CursedSkull => new NpcType(34);
		public static NpcType CyanBeetle => new NpcType(218);
		public static NpcType Cyborg => new NpcType(209);
		public static NpcType DarkCaster => new NpcType(32);
		public static NpcType DarkMummy => new NpcType(79);
		public static NpcType DeadlySphere => new NpcType(467);
		public static NpcType Demolitionist => new NpcType(38);
		public static NpcType Demon => new NpcType(62);
		public static NpcType DemonEye => new NpcType(2);
		public static NpcType DemonEye2 => new NpcType(-43);
		public static NpcType DemonEyeOwl => new NpcType(317);
		public static NpcType DemonEyeSpaceship => new NpcType(318);
		public static NpcType DemonTaxCollector => new NpcType(534);
		public static NpcType Derpling => new NpcType(177);
		public static NpcType DesertBeast => new NpcType(532);
		public static NpcType DesertDjinn => new NpcType(533);
		public static NpcType DesertGhoul => new NpcType(524);
		public static NpcType DesertGhoulCorruption => new NpcType(525);
		public static NpcType DesertGhoulCrimson => new NpcType(526);
		public static NpcType DesertGhoulHallow => new NpcType(527);
		public static NpcType DesertLamiaDark => new NpcType(529);
		public static NpcType DesertLamiaLight => new NpcType(528);
		public static NpcType DesertScorpionWalk => new NpcType(530);
		public static NpcType DesertScorpionWall => new NpcType(531);
		public static NpcType DetonatingBubble => new NpcType(371);
		public static NpcType DevourerBody => new NpcType(8);
		public static NpcType DevourerHead => new NpcType(7);
		public static NpcType DevourerTail => new NpcType(9);
		public static NpcType DiabolistRed => new NpcType(285);
		public static NpcType DiabolistWhite => new NpcType(286);
		public static NpcType DialatedEye => new NpcType(192);
		public static NpcType DialatedEye2 => new NpcType(-40);
		public static NpcType DiggerBody => new NpcType(96);
		public static NpcType DiggerHead => new NpcType(95);
		public static NpcType DiggerTail => new NpcType(97);
		public static NpcType DoctorBones => new NpcType(52);
		public static NpcType Drippler => new NpcType(490);
		public static NpcType DrManFly => new NpcType(468);
		public static NpcType Dryad => new NpcType(20);
		public static NpcType Duck => new NpcType(362);
		public static NpcType Duck2 => new NpcType(363);
		public static NpcType DuckWhite => new NpcType(364);
		public static NpcType DuckWhite2 => new NpcType(365);
		public static NpcType DukeFishron => new NpcType(370);
		public static NpcType DuneSplicerBody => new NpcType(511);
		public static NpcType DuneSplicerHead => new NpcType(510);
		public static NpcType DuneSplicerTail => new NpcType(512);
		public static NpcType DungeonGuardian => new NpcType(68);
		public static NpcType DungeonSlime => new NpcType(71);
		public static NpcType DungeonSpirit => new NpcType(288);
		public static NpcType DyeTrader => new NpcType(207);
		public static NpcType EaterofSouls => new NpcType(6);
		public static NpcType EaterofWorldsBody => new NpcType(14);
		public static NpcType EaterofWorldsHead => new NpcType(13);
		public static NpcType EaterofWorldsTail => new NpcType(15);
		public static NpcType ElfArcher => new NpcType(350);
		public static NpcType ElfCopter => new NpcType(347);
		public static NpcType EnchantedNightcrawler => new NpcType(484);
		public static NpcType EnchantedSword => new NpcType(84);
		public static NpcType Everscream => new NpcType(344);
		public static NpcType EyeofCthulhu => new NpcType(4);
		public static NpcType Eyezor => new NpcType(251);
		public static NpcType FaceMonster => new NpcType(181);
		public static NpcType FemaleZombie => new NpcType(200);
		public static NpcType Firefly => new NpcType(355);
		public static NpcType FireImp => new NpcType(24);
		public static NpcType FloatyGross => new NpcType(182);
		public static NpcType Flocko => new NpcType(352);
		public static NpcType FlyingAntlion => new NpcType(509);
		public static NpcType FlyingFish => new NpcType(224);
		public static NpcType FlyingSnake => new NpcType(226);
		public static NpcType ForceBubble => new NpcType(384);
		public static NpcType Frankenstein => new NpcType(162);
		public static NpcType Fritz => new NpcType(462);
		public static NpcType Frog => new NpcType(361);
		public static NpcType FungiBulb => new NpcType(259);
		public static NpcType FungiSpore => new NpcType(261);
		public static NpcType FungoFish => new NpcType(256);
		public static NpcType Gastropod => new NpcType(122);
		public static NpcType Ghost => new NpcType(316);
		public static NpcType GiantBat => new NpcType(93);
		public static NpcType GiantCursedSkull => new NpcType(289);
		public static NpcType GiantFlyingFox => new NpcType(152);
		public static NpcType GiantFungiBulb => new NpcType(260);
		public static NpcType GiantMossHornet => new NpcType(-21);
		public static NpcType GiantShelly => new NpcType(496);
		public static NpcType GiantShelly2 => new NpcType(497);
		public static NpcType GiantTortoise => new NpcType(153);
		public static NpcType GiantWormBody => new NpcType(11);
		public static NpcType GiantWormHead => new NpcType(10);
		public static NpcType GiantWormTail => new NpcType(12);
		public static NpcType GigaZapper => new NpcType(389);
		public static NpcType GingerbreadMan => new NpcType(342);
		public static NpcType GlowingSnail => new NpcType(360);
		public static NpcType GoblinArcher => new NpcType(111);
		public static NpcType GoblinPeon => new NpcType(26);
		public static NpcType GoblinScout => new NpcType(73);
		public static NpcType GoblinSorcerer => new NpcType(29);
		public static NpcType GoblinSummoner => new NpcType(471);
		public static NpcType GoblinThief => new NpcType(27);
		public static NpcType GoblinTinkerer => new NpcType(107);
		public static NpcType GoblinWarrior => new NpcType(28);
		public static NpcType GoldBird => new NpcType(442);
		public static NpcType GoldBunny => new NpcType(443);
		public static NpcType GoldButterfly => new NpcType(444);
		public static NpcType Goldfish => new NpcType(55);
		public static NpcType GoldfishWalker => new NpcType(230);
		public static NpcType GoldFrog => new NpcType(445);
		public static NpcType GoldGrasshopper => new NpcType(446);
		public static NpcType GoldMouse => new NpcType(447);
		public static NpcType GoldWorm => new NpcType(448);
		public static NpcType Golem => new NpcType(245);
		public static NpcType GolemFistLeft => new NpcType(247);
		public static NpcType GolemFistRight => new NpcType(248);
		public static NpcType GolemHead => new NpcType(246);
		public static NpcType GolemHeadFree => new NpcType(249);
		public static NpcType GraniteFlyer => new NpcType(483);
		public static NpcType GraniteGolem => new NpcType(482);
		public static NpcType Grasshopper => new NpcType(377);
		public static NpcType GrayGrunt => new NpcType(385);
		public static NpcType GreekSkeleton => new NpcType(481);
		public static NpcType GreenEye => new NpcType(193);
		public static NpcType GreenEye2 => new NpcType(-41);
		public static NpcType GreenJellyfish => new NpcType(103);
		public static NpcType GreenSlime => new NpcType(-3);
		public static NpcType Grubby => new NpcType(485);
		public static NpcType Guide => new NpcType(22);
		public static NpcType Harpy => new NpcType(48);
		public static NpcType HeadacheSkeleton => new NpcType(201);
		public static NpcType HeadlessHorseman => new NpcType(315);
		public static NpcType HeavySkeleton => new NpcType(-15);
		public static NpcType HellArmoredBones => new NpcType(277);
		public static NpcType HellArmoredBonesMace => new NpcType(279);
		public static NpcType HellArmoredBonesSpikeShield => new NpcType(278);
		public static NpcType HellArmoredBonesSword => new NpcType(280);
		public static NpcType Hellbat => new NpcType(60);
		public static NpcType Hellhound => new NpcType(329);
		public static NpcType Herpling => new NpcType(174);
		public static NpcType HoppinJack => new NpcType(304);
		public static NpcType Hornet => new NpcType(42);
		public static NpcType HornetFatty => new NpcType(231);
		public static NpcType HornetHoney => new NpcType(232);
		public static NpcType HornetLeafy => new NpcType(233);
		public static NpcType HornetSpikey => new NpcType(234);
		public static NpcType HornetStingy => new NpcType(235);
		public static NpcType IceBat => new NpcType(150);
		public static NpcType IceElemental => new NpcType(169);
		public static NpcType IceGolem => new NpcType(243);
		public static NpcType IceQueen => new NpcType(345);
		public static NpcType IceSlime => new NpcType(147);
		public static NpcType IceTortoise => new NpcType(154);
		public static NpcType IchorSticker => new NpcType(268);
		public static NpcType IcyMerman => new NpcType(206);
		public static NpcType IlluminantBat => new NpcType(137);
		public static NpcType IlluminantSlime => new NpcType(138);
		public static NpcType JungleBat => new NpcType(51);
		public static NpcType JungleCreeper => new NpcType(236);
		public static NpcType JungleCreeperWall => new NpcType(237);
		public static NpcType JungleSlime => new NpcType(-10);
		public static NpcType KingSlime => new NpcType(50);
		public static NpcType Krampus => new NpcType(351);
		public static NpcType LacBeetle => new NpcType(219);
		public static NpcType Lavabat => new NpcType(151);
		public static NpcType LavaSlime => new NpcType(59);
		public static NpcType LeechBody => new NpcType(118);
		public static NpcType LeechHead => new NpcType(117);
		public static NpcType LeechTail => new NpcType(119);
		public static NpcType LightMummy => new NpcType(80);
		public static NpcType LightningBug => new NpcType(358);
		public static NpcType Lihzahrd => new NpcType(198);
		public static NpcType LihzahrdCrawler => new NpcType(199);
		public static NpcType LittleCrimera => new NpcType(-22);
		public static NpcType LittleCrimslime => new NpcType(-24);
		public static NpcType LittleEater => new NpcType(-11);
		public static NpcType LittleHornetFatty => new NpcType(-56);
		public static NpcType LittleHornetHoney => new NpcType(-58);
		public static NpcType LittleHornetLeafy => new NpcType(-60);
		public static NpcType LittleHornetSpikey => new NpcType(-62);
		public static NpcType LittleHornetStingy => new NpcType(-64);
		public static NpcType LittleMossHornet => new NpcType(-19);
		public static NpcType LittleStinger => new NpcType(-16);
		public static NpcType LostGirl => new NpcType(195);
		public static NpcType LunarTowerNebula => new NpcType(507);
		public static NpcType LunarTowerSolar => new NpcType(517);
		public static NpcType LunarTowerStardust => new NpcType(493);
		public static NpcType LunarTowerVortex => new NpcType(422);
		public static NpcType ManEater => new NpcType(43);
		public static NpcType MartianDrone => new NpcType(388);
		public static NpcType MartianEngineer => new NpcType(386);
		public static NpcType MartianOfficer => new NpcType(383);
		public static NpcType MartianProbe => new NpcType(399);
		public static NpcType MartianSaucer => new NpcType(392);
		public static NpcType MartianSaucerCannon => new NpcType(394);
		public static NpcType MartianSaucerCore => new NpcType(395);
		public static NpcType MartianSaucerTurret => new NpcType(393);
		public static NpcType MartianTurret => new NpcType(387);
		public static NpcType MartianWalker => new NpcType(520);
		public static NpcType Mechanic => new NpcType(124);
		public static NpcType Medusa => new NpcType(480);
		public static NpcType Merchant => new NpcType(17);
		public static NpcType MeteorHead => new NpcType(23);
		public static NpcType Mimic => new NpcType(85);
		public static NpcType MisassembledSkeleton => new NpcType(202);
		public static NpcType MisterStabby => new NpcType(144);
		public static NpcType MoonLordCore => new NpcType(398);
		public static NpcType MoonLordFreeEye => new NpcType(400);
		public static NpcType MoonLordHand => new NpcType(397);
		public static NpcType MoonLordHead => new NpcType(396);
		public static NpcType MoonLordLeechBlob => new NpcType(401);
		public static NpcType MossHornet => new NpcType(176);
		public static NpcType Moth => new NpcType(205);
		public static NpcType MotherSlime => new NpcType(16);
		public static NpcType Mothron => new NpcType(477);
		public static NpcType MothronEgg => new NpcType(478);
		public static NpcType MothronSpawn => new NpcType(479);
		public static NpcType MourningWood => new NpcType(325);
		public static NpcType Mouse => new NpcType(300);
		public static NpcType Mummy => new NpcType(78);
		public static NpcType MushiLadybug => new NpcType(258);
		public static NpcType Nailhead => new NpcType(463);
		public static NpcType NebulaBeast => new NpcType(423);
		public static NpcType NebulaBrain => new NpcType(420);
		public static NpcType NebulaHeadcrab => new NpcType(421);
		public static NpcType NebulaSoldier => new NpcType(424);
		public static NpcType Necromancer => new NpcType(283);
		public static NpcType NecromancerArmored => new NpcType(284);
		public static NpcType None => new NpcType(0);
		public static NpcType None2 => new NpcType(76);
		public static NpcType None3 => new NpcType(146);
		public static NpcType Nurse => new NpcType(18);
		public static NpcType Nutcracker => new NpcType(348);
		public static NpcType NutcrackerSpinning => new NpcType(349);
		public static NpcType Nymph => new NpcType(196);
		public static NpcType OldMan => new NpcType(37);
		public static NpcType Painter => new NpcType(227);
		public static NpcType Paladin => new NpcType(290);
		public static NpcType PantlessSkeleton => new NpcType(203);
		public static NpcType Parrot => new NpcType(252);
		public static NpcType PartyBunny => new NpcType(540);
		public static NpcType PartyGirl => new NpcType(208);
		public static NpcType Penguin => new NpcType(148);
		public static NpcType PenguinBlack => new NpcType(149);
		public static NpcType PigronCorruption => new NpcType(170);
		public static NpcType PigronCrimson => new NpcType(180);
		public static NpcType PigronHallow => new NpcType(171);
		public static NpcType PincushionZombie => new NpcType(186);
		public static NpcType PinkJellyfish => new NpcType(64);
		public static NpcType Pinky => new NpcType(-4);
		public static NpcType Piranha => new NpcType(58);
		public static NpcType Pirate => new NpcType(229);
		public static NpcType PirateCaptain => new NpcType(216);
		public static NpcType PirateCorsair => new NpcType(213);
		public static NpcType PirateCrossbower => new NpcType(215);
		public static NpcType PirateDeadeye => new NpcType(214);
		public static NpcType PirateDeckhand => new NpcType(212);
		public static NpcType PirateShip => new NpcType(491);
		public static NpcType PirateShipCannon => new NpcType(492);
		public static NpcType Pixie => new NpcType(75);
		public static NpcType Plantera => new NpcType(262);
		public static NpcType PlanterasHook => new NpcType(263);
		public static NpcType PlanterasTentacle => new NpcType(264);
		public static NpcType Poltergeist => new NpcType(330);
		public static NpcType PossessedArmor => new NpcType(140);
		public static NpcType PresentMimic => new NpcType(341);
		public static NpcType PrimeCannon => new NpcType(128);
		public static NpcType PrimeLaser => new NpcType(131);
		public static NpcType PrimeSaw => new NpcType(129);
		public static NpcType PrimeVice => new NpcType(130);
		public static NpcType Probe => new NpcType(139);
		public static NpcType Psycho => new NpcType(466);
		public static NpcType Pumpking => new NpcType(327);
		public static NpcType PumpkingBlade => new NpcType(328);
		public static NpcType PurpleEye => new NpcType(194);
		public static NpcType PurpleEye2 => new NpcType(-42);
		public static NpcType PurpleSlime => new NpcType(-7);
		public static NpcType QueenBee => new NpcType(222);
		public static NpcType RaggedCaster => new NpcType(281);
		public static NpcType RaggedCasterOpenCoat => new NpcType(282);
		public static NpcType RainbowSlime => new NpcType(244);
		public static NpcType Raven => new NpcType(301);
		public static NpcType RayGunner => new NpcType(382);
		public static NpcType Reaper => new NpcType(253);
		public static NpcType RedDevil => new NpcType(156);
		public static NpcType RedSlime => new NpcType(-8);
		public static NpcType Retinazer => new NpcType(125);
		public static NpcType RuneWizard => new NpcType(172);
		public static NpcType RustyArmoredBonesAxe => new NpcType(269);
		public static NpcType RustyArmoredBonesFlail => new NpcType(270);
		public static NpcType RustyArmoredBonesSword => new NpcType(271);
		public static NpcType RustyArmoredBonesSwordNoArmor => new NpcType(272);
		public static NpcType Salamander => new NpcType(498);
		public static NpcType Salamander2 => new NpcType(499);
		public static NpcType Salamander3 => new NpcType(500);
		public static NpcType Salamander4 => new NpcType(501);
		public static NpcType Salamander5 => new NpcType(502);
		public static NpcType Salamander6 => new NpcType(503);
		public static NpcType Salamander7 => new NpcType(504);
		public static NpcType Salamander8 => new NpcType(505);
		public static NpcType Salamander9 => new NpcType(506);
		public static NpcType SandSlime => new NpcType(537);
		public static NpcType SantaClaus => new NpcType(142);
		public static NpcType SantaNK1 => new NpcType(346);
		public static NpcType Scarecrow1 => new NpcType(305);
		public static NpcType Scarecrow10 => new NpcType(314);
		public static NpcType Scarecrow2 => new NpcType(306);
		public static NpcType Scarecrow3 => new NpcType(307);
		public static NpcType Scarecrow4 => new NpcType(308);
		public static NpcType Scarecrow5 => new NpcType(309);
		public static NpcType Scarecrow6 => new NpcType(310);
		public static NpcType Scarecrow7 => new NpcType(311);
		public static NpcType Scarecrow8 => new NpcType(312);
		public static NpcType Scarecrow9 => new NpcType(313);
		public static NpcType Scorpion => new NpcType(367);
		public static NpcType ScorpionBlack => new NpcType(366);
		public static NpcType Scutlix => new NpcType(391);
		public static NpcType ScutlixRider => new NpcType(390);
		public static NpcType SeaSnail => new NpcType(220);
		public static NpcType SeekerBody => new NpcType(99);
		public static NpcType SeekerHead => new NpcType(98);
		public static NpcType SeekerTail => new NpcType(100);
		public static NpcType ServantofCthulhu => new NpcType(5);
		public static NpcType ShadowFlameApparition => new NpcType(472);
		public static NpcType Shark => new NpcType(65);
		public static NpcType Sharkron => new NpcType(372);
		public static NpcType Sharkron2 => new NpcType(373);
		public static NpcType ShortBones => new NpcType(-13);
		public static NpcType Skeleton => new NpcType(21);
		public static NpcType SkeletonAlien => new NpcType(324);
		public static NpcType SkeletonArcher => new NpcType(110);
		public static NpcType SkeletonAstonaut => new NpcType(323);
		public static NpcType SkeletonCommando => new NpcType(293);
		public static NpcType SkeletonMerchant => new NpcType(453);
		public static NpcType SkeletonSniper => new NpcType(291);
		public static NpcType SkeletonTopHat => new NpcType(322);
		public static NpcType SkeletronHand => new NpcType(36);
		public static NpcType SkeletronHead => new NpcType(35);
		public static NpcType SkeletronPrime => new NpcType(127);
		public static NpcType SleepingAngler => new NpcType(376);
		public static NpcType SleepyEye => new NpcType(191);
		public static NpcType SleepyEye2 => new NpcType(-39);
		public static NpcType SlimedZombie => new NpcType(187);
		public static NpcType Slimeling => new NpcType(-1);
		public static NpcType SlimeMasked => new NpcType(302);
		public static NpcType Slimer => new NpcType(121);
		public static NpcType Slimer2 => new NpcType(-2);
		public static NpcType SlimeRibbonGreen => new NpcType(335);
		public static NpcType SlimeRibbonRed => new NpcType(336);
		public static NpcType SlimeRibbonWhite => new NpcType(333);
		public static NpcType SlimeRibbonYellow => new NpcType(334);
		public static NpcType SlimeSpiked => new NpcType(535);
		public static NpcType Sluggy => new NpcType(486);
		public static NpcType SmallBaldZombie => new NpcType(-28);
		public static NpcType SmallFemaleZombie => new NpcType(-44);
		public static NpcType SmallHeadacheSkeleton => new NpcType(-48);
		public static NpcType SmallMisassembledSkeleton => new NpcType(-50);
		public static NpcType SmallPantlessSkeleton => new NpcType(-52);
		public static NpcType SmallPincushionZombie => new NpcType(-30);
		public static NpcType SmallRainZombie => new NpcType(-54);
		public static NpcType SmallSkeleton => new NpcType(-46);
		public static NpcType SmallSlimedZombie => new NpcType(-32);
		public static NpcType SmallSwampZombie => new NpcType(-34);
		public static NpcType SmallTwiggyZombie => new NpcType(-36);
		public static NpcType SmallZombie => new NpcType(-26);
		public static NpcType Snail => new NpcType(359);
		public static NpcType Snatcher => new NpcType(56);
		public static NpcType SnowBalla => new NpcType(145);
		public static NpcType SnowFlinx => new NpcType(185);
		public static NpcType SnowmanGangsta => new NpcType(143);
		public static NpcType SolarCorite => new NpcType(418);
		public static NpcType SolarCrawltipedeBody => new NpcType(413);
		public static NpcType SolarCrawltipedeHead => new NpcType(412);
		public static NpcType SolarCrawltipedeTail => new NpcType(414);
		public static NpcType SolarDrakomire => new NpcType(415);
		public static NpcType SolarDrakomireRider => new NpcType(416);
		public static NpcType SolarFlare => new NpcType(516);
		public static NpcType SolarGoop => new NpcType(519);
		public static NpcType SolarSolenian => new NpcType(419);
		public static NpcType SolarSpearman => new NpcType(518);
		public static NpcType SolarSroller => new NpcType(417);
		public static NpcType Spazmatism => new NpcType(126);
		public static NpcType SpikeBall => new NpcType(70);
		public static NpcType SpikedIceSlime => new NpcType(184);
		public static NpcType SpikedJungleSlime => new NpcType(204);
		public static NpcType Splinterling => new NpcType(326);
		public static NpcType Spore => new NpcType(265);
		public static NpcType Squid => new NpcType(221);
		public static NpcType Squirrel => new NpcType(299);
		public static NpcType SquirrelGold => new NpcType(539);
		public static NpcType SquirrelRed => new NpcType(538);
		public static NpcType StardustCellBig => new NpcType(405);
		public static NpcType StardustCellSmall => new NpcType(406);
		public static NpcType StardustJellyfishBig => new NpcType(407);
		public static NpcType StardustJellyfishSmall => new NpcType(408);
		public static NpcType StardustSoldier => new NpcType(411);
		public static NpcType StardustSpiderBig => new NpcType(409);
		public static NpcType StardustSpiderSmall => new NpcType(410);
		public static NpcType StardustWormBody => new NpcType(403);
		public static NpcType StardustWormHead => new NpcType(402);
		public static NpcType StardustWormTail => new NpcType(404);
		public static NpcType Steampunker => new NpcType(178);
		public static NpcType Stylist => new NpcType(353);
		public static NpcType SwampThing => new NpcType(166);
		public static NpcType SwampZombie => new NpcType(188);
		public static NpcType TacticalSkeleton => new NpcType(292);
		public static NpcType TargetDummy => new NpcType(488);
		public static NpcType TaxCollector => new NpcType(441);
		public static NpcType TheBride => new NpcType(536);
		public static NpcType TheDestroyer => new NpcType(134);
		public static NpcType TheDestroyerBody => new NpcType(135);
		public static NpcType TheDestroyerTail => new NpcType(136);
		public static NpcType TheGroom => new NpcType(53);
		public static NpcType TheHungry => new NpcType(115);
		public static NpcType TheHungryII => new NpcType(116);
		public static NpcType ThePossessed => new NpcType(469);
		public static NpcType Tim => new NpcType(45);
		public static NpcType TinyMossHornet => new NpcType(-18);
		public static NpcType TombCrawlerBody => new NpcType(514);
		public static NpcType TombCrawlerHead => new NpcType(513);
		public static NpcType TombCrawlerTail => new NpcType(515);
		public static NpcType ToxicSludge => new NpcType(141);
		public static NpcType TravellingMerchant => new NpcType(368);
		public static NpcType Truffle => new NpcType(160);
		public static NpcType TruffleWorm => new NpcType(374);
		public static NpcType TruffleWormDigger => new NpcType(375);
		public static NpcType TwiggyZombie => new NpcType(189);
		public static NpcType UmbrellaSlime => new NpcType(225);
		public static NpcType UndeadMiner => new NpcType(44);
		public static NpcType UndeadViking => new NpcType(167);
		public static NpcType Unicorn => new NpcType(86);
		public static NpcType Vampire => new NpcType(159);
		public static NpcType VampireBat => new NpcType(158);
		public static NpcType VileSpit => new NpcType(112);
		public static NpcType VoodooDemon => new NpcType(66);
		public static NpcType VortexHornet => new NpcType(427);
		public static NpcType VortexHornetQueen => new NpcType(426);
		public static NpcType VortexLarva => new NpcType(428);
		public static NpcType VortexRifleman => new NpcType(425);
		public static NpcType VortexSoldier => new NpcType(429);
		public static NpcType Vulture => new NpcType(61);
		public static NpcType WalkingAntlion => new NpcType(508);
		public static NpcType WallCreeper => new NpcType(164);
		public static NpcType WallCreeperWall => new NpcType(165);
		public static NpcType WallofFlesh => new NpcType(113);
		public static NpcType WallofFleshEye => new NpcType(114);
		public static NpcType WanderingEye => new NpcType(133);
		public static NpcType WaterSphere => new NpcType(33);
		public static NpcType WebbedStylist => new NpcType(354);
		public static NpcType Werewolf => new NpcType(104);
		public static NpcType WitchDoctor => new NpcType(228);
		public static NpcType Wizard => new NpcType(108);
		public static NpcType Wolf => new NpcType(155);
		public static NpcType Worm => new NpcType(357);
		public static NpcType Wraith => new NpcType(82);
		public static NpcType WyvernBody => new NpcType(89);
		public static NpcType WyvernBody2 => new NpcType(90);
		public static NpcType WyvernBody3 => new NpcType(91);
		public static NpcType WyvernHead => new NpcType(87);
		public static NpcType WyvernLegs => new NpcType(88);
		public static NpcType WyvernTail => new NpcType(92);
		public static NpcType YellowSlime => new NpcType(-9);
		public static NpcType Yeti => new NpcType(343);
		public static NpcType Zombie => new NpcType(3);
		public static NpcType ZombieDoctor => new NpcType(319);
		public static NpcType ZombieElf => new NpcType(338);
		public static NpcType ZombieElfBeard => new NpcType(339);
		public static NpcType ZombieElfGirl => new NpcType(340);
		public static NpcType ZombieEskimo => new NpcType(161);
		public static NpcType ZombieMushroom => new NpcType(254);
		public static NpcType ZombieMushroomHat => new NpcType(255);
		public static NpcType ZombiePixie => new NpcType(321);
		public static NpcType ZombieRaincoat => new NpcType(223);
		public static NpcType ZombieSuperman => new NpcType(320);
		public static NpcType ZombieSweater => new NpcType(332);
		public static NpcType ZombieXmas => new NpcType(331);
#pragma warning restore 1591

		/// <summary>
		/// Determines if two <see cref="NpcType"/> instances are equal.
		/// </summary>
		/// <param name="type1">The first <see cref="NpcType"/> instance.</param>
		/// <param name="type2">The second <see cref="NpcType"/> instance.</param>
		/// <returns>true if <paramref name="type1"/> equals <paramref name="type2"/>, false otherwise.</returns>
		public static bool operator ==(NpcType type1, NpcType type2) => type1.Equals(type2);

		/// <summary>
		/// Converts a <see cref="NpcType"/> instance into its integer representation.
		/// </summary>
		/// <param name="type">The <see cref="NpcType"/> instance.</param>
		public static implicit operator int(NpcType type) => type._type;

		/// <summary>
		/// Converts an integer into its <see cref="NpcType"/> representation.
		/// </summary>
		/// <param name="i">The integer.</param>
		public static implicit operator NpcType(int i) => new NpcType(i);

		/// <summary>
		/// Determines if two <see cref="NpcType"/> instances are not equal.
		/// </summary>
		/// <param name="type1">The first <see cref="NpcType"/> instance.</param>
		/// <param name="type2">The second <see cref="NpcType"/> instance.</param>
		/// <returns>
		/// true if <paramref name="type1"/> does not equal <paramref name="type2"/>, false otherwise.
		/// </returns>
		public static bool operator !=(NpcType type1, NpcType type2) => !type1.Equals(type2);

		private readonly int _type;

		/// <summary>
		/// Initializes a new instance of the <see cref="NpcType"/> structure with the specified NPC
		/// type.
		/// </summary>
		/// <param name="type">The NPC type.</param>
		public NpcType(int type)
		{
			_type = type;
		}

		/// <summary>
		/// Determines if this instance equals another <see cref="NpcType"/> instance.
		/// </summary>
		/// <param name="other">The other <see cref="NpcType"/> instance.</param>
		/// <returns>true if this instance equals <paramref name="other"/>, false otherwise.</returns>
		public bool Equals(NpcType other) => _type == other._type;

		/// <summary>
		/// Determines if this instance equals another object instance.
		/// </summary>
		/// <param name="obj">The other object instance.</param>
		/// <returns>true if this instance equals <paramref name="obj"/>, false otherwise.</returns>
		public override bool Equals(object obj) => obj is NpcType && Equals((NpcType)obj);

		/// <summary>
		/// Gets the hash code for this instance.
		/// </summary>
		/// <returns>The hash code for this instance.</returns>
		public override int GetHashCode() => _type;

		/// <summary>
		/// Returns the string representation of this instance.
		/// </summary>
		/// <returns>The string representation of this instance.</returns>
		public override string ToString() => $"{_type}";
	}
}
