// Copyright (c) 2019 Pryaxis & Orion Contributors
// 
// This file is part of Orion.
// 
// Orion is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Orion is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Orion.  If not, see <https://www.gnu.org/licenses/>.

using System.Collections.Generic;
using System.Diagnostics.Contracts;

namespace Orion.World.Tiles {
    /// <summary>
    /// Specifies a block type.
    /// </summary>
    public enum BlockType : ushort {
#pragma warning disable 1591
        Dirt = 0,
        Stone = 1,
        Grass = 2,
        ShortGrassPlants = 3,
        Torches = 4,
        Trees = 5,
        IronOre = 6,
        CopperOre = 7,
        GoldOre = 8,
        SilverOre = 9,
        ClosedDoors = 10,
        OpenDoors = 11,
        CrystalHeart = 12,
        Bottles = 13,
        Tables = 14,
        Chairs = 15,
        Anvils = 16,
        Furnace = 17,
        WorkBenches = 18,
        Platforms = 19,
        Saplings = 20,
        Chests = 21,
        DemoniteOre = 22,
        CorruptGrass = 23,
        ShortCorruptionPlants = 24,
        Ebonstone = 25,
        Altars = 26,
        Sunflower = 27,
        Pot = 28,
        PiggyBank = 29,
        Wood = 30,
        ShadowOrbs = 31,
        CorruptionThorn = 32,
        Candles = 33,
        Chandeliers = 34,
        JackOLantern = 35,
        Present = 36,
        Meteorite = 37,
        GrayBrick = 38,
        RedBrick = 39,
        Clay = 40,
        BlueBrick = 41,
        Lanterns = 42,
        GreenBrick = 43,
        PinkBrick = 44,
        GoldBrick = 45,
        SilverBrick = 46,
        CopperBrick = 47,
        Spike = 48,
        WaterCandle = 49,
        Book = 50,
        Cobweb = 51,
        Vine = 52,
        Sand = 53,
        Glass = 54,
        Sign = 55,
        Obsidian = 56,
        Ash = 57,
        Hellstone = 58,
        Mud = 59,
        JungleGrass = 60,
        ShortJunglePlants = 61,
        JungleVine = 62,
        SapphireOre = 63,
        RubyOre = 64,
        EmeraldOre = 65,
        TopazOre = 66,
        AmethystOre = 67,
        DiamondOre = 68,
        JungleThorn = 69,
        MushroomGrass = 70,
        MushroomPlants = 71,
        MushroomTrees = 72,
        TallGrassPlants = 73,
        TallJunglePlants = 74,
        ObsidianBrick = 75,
        HellstoneBrick = 76,
        Hellforge = 77,
        ClayPot = 78,
        Beds = 79,
        CactusPlant = 80,
        Coral = 81,
        GrowingHerbs = 82,
        MatureHerbs = 83,
        BloomingHerbs = 84,
        Tombstones = 85,
        Loom = 86,
        Pianos = 87,
        Dressers = 88,
        Benches = 89,
        Bathtubs = 90,
        Banners = 91,
        LampPost = 92,
        Lamps = 93,
        Keg = 94,
        ChineseLantern = 95,
        CookingPots = 96,
        Safe = 97,
        SkullLantern = 98,
        Candelabras = 100,
        Bookcases = 101,
        Throne = 102,
        Bowls = 103,
        Clocks = 104,
        Statues = 105,
        Sawmill = 106,
        CobaltOre = 107,
        MythrilOre = 108,
        HallowedGrass = 109,
        ShortHallowedPlants = 110,
        AdamantiteOre = 111,
        Ebonsand = 112,
        TallHallowedPlants = 113,
        TinkerersWorkshop = 114,
        HallowedVine = 115,
        Pearlsand = 116,
        Pearlstone = 117,
        PearlstoneBrick = 118,
        IridescentBrick = 119,
        MudstoneBrick = 120,
        CobaltBrick = 121,
        MythrilBrick = 122,
        Silt = 123,
        WoodenBeam = 124,
        CrystalBall = 125,
        DiscoBall = 126,
        IceRod = 127,
        Mannequin = 128,
        CrystalShard = 129,
        ActiveStone = 130,
        InactiveStone = 131,
        Lever = 132,
        Forges = 133,
        HardmodeAnvils = 134,
        PressurePlates = 135,
        Switch = 136,
        Traps = 137,
        Boulder = 138,
        MusicBoxes = 139,
        DemoniteBrick = 140,
        Explosives = 141,
        InletPump = 142,
        OutletPump = 143,
        Timers = 144,
        CandyCane = 145,
        GreenCandyCane = 146,
        Snow = 147,
        SnowBrick = 148,
        ChristmasLights = 149,
        AdamantiteBeam = 150,
        SandstoneBrick = 151,
        EbonstoneBrick = 152,
        RedStucco = 153,
        YellowStucco = 154,
        GreenStucco = 155,
        GrayStucco = 156,
        Ebonwood = 157,
        RichMahogany = 158,
        Pearlwood = 159,
        RainbowBrick = 160,
        Ice = 161,
        ThinIce = 162,
        PurpleIce = 163,
        PinkIce = 164,
        AmbientObjects = 165,
        TinOre = 166,
        LeadOre = 167,
        TungstenOre = 168,
        PlatinumOre = 169,
        PineTree = 170,
        ChristmasTree = 171,
        Sinks = 172,
        PlatinumCandelabra = 173,
        PlatinumCandle = 174,
        TinBrick = 175,
        TungstenBrick = 176,
        PlatinumBrick = 177,
        Gems = 178,
        TealMoss = 179,
        ChartreuseMoss = 180,
        RedMoss = 181,
        BlueMoss = 182,
        PurpleMoss = 183,
        MossGrowth = 184,
        SmallAmbientObjects = 185,
        LargeAmbientObjects = 186,
        LargeAmbientObjects2 = 187,
        Cactus = 188,
        Cloud = 189,
        GlowingMushroom = 190,
        LivingWood = 191,
        Leaf = 192,
        Slime = 193,
        Bone = 194,
        Flesh = 195,
        RainCloud = 196,
        FrozenSlime = 197,
        Asphalt = 198,
        CrimsonGrass = 199,
        RedIce = 200,
        ShortCrimsonPlants = 201,
        Sunplate = 202,
        Crimstone = 203,
        CrimtaneOre = 204,
        CrimsonVine = 205,
        IceBrick = 206,
        WaterFountains = 207,
        Shadewood = 208,
        Cannons = 209,
        LandMine = 210,
        ChlorophyteOre = 211,
        SnowballLauncher = 212,
        Rope = 213,
        Chain = 214,
        Campfires = 215,
        Rockets = 216,
        BlendOMatic = 217,
        MeatGrinder = 218,
        Extractinator = 219,
        Solidifier = 220,
        PalladiumOre = 221,
        OrichalcumOre = 222,
        TitaniumOre = 223,
        Slush = 224,
        Hive = 225,
        LihzahrdBrick = 226,
        DyePlants = 227,
        DyeVat = 228,
        Honey = 229,
        CrispyHoney = 230,
        Larva = 231,
        WoodenSpike = 232,
        PlantDetritus = 233,
        Crimsand = 234,
        Teleporter = 235,
        LifeFruit = 236,
        LihzahrdAltar = 237,
        PlanterasBulb = 238,
        MetalBars = 239,
        Paintings3x3 = 240,
        Paintings4x3 = 241,
        Paintings6x4 = 242,
        ImbuingStation = 243,
        BubbleMachine = 244,
        Paintings2x3 = 245,
        Paintings3x2 = 246,
        Autohammer = 247,
        PalladiumColumn = 248,
        Bubblegum = 249,
        Titanstone = 250,
        Pumpkin = 251,
        Hay = 252,
        SpookyWood = 253,
        PumpkinPlants = 254,
        OfflineAmethystGemspark = 255,
        OfflineTopazGemspark = 256,
        OfflineSapphireGemspark = 257,
        OfflineEmeraldGemspark = 258,
        OfflineRubyGemspark = 259,
        OfflineDiamondGemspark = 260,
        OfflineAmberGemspark = 261,
        AmethystGemspark = 262,
        TopazGemspark = 263,
        SapphireGemspark = 264,
        EmeraldGemspark = 265,
        RubyGemspark = 266,
        DiamondGemspark = 267,
        AmberGemspark = 268,
        Womannequin = 269,
        FireflyInABottle = 270,
        LightningBugInABottle = 271,
        Cog = 272,
        StoneSlab = 273,
        SandstoneSlab = 274,
        BunnyCage = 275,
        SquirrelCage = 276,
        MallardDuckCage = 277,
        DuckCage = 278,
        BirdCage = 279,
        BlueJayCage = 280,
        CardinalCage = 281,
        FishBowl = 282,
        HeavyWorkBench = 283,
        CopperPlating = 284,
        SnailCage = 285,
        GlowingSnailCage = 286,
        AmmoBox = 287,
        MonarchButterflyJar = 288,
        PurpleEmperorButterflyJar = 289,
        RedAdmiralButterflyJar = 290,
        UlyssesButterflyJar = 291,
        SulphurButterflyJar = 292,
        TreeNymphButterflyJar = 293,
        ZebraSwallowtailButterflyJar = 294,
        JuliaButterflyJar = 295,
        ScorpionCage = 296,
        BlackScorpionCage = 297,
        FrogCage = 298,
        MouseCage = 299,
        BoneWelder = 300,
        FleshCloningVat = 301,
        GlassKiln = 302,
        LihzahrdFurnace = 303,
        LivingLoom = 304,
        SkyMill = 305,
        IceMachine = 306,
        SteampunkBoiler = 307,
        HoneyDispenser = 308,
        PenguinCage = 309,
        WormCage = 310,
        DynastyWood = 311,
        RedDynastyShingles = 312,
        BlueDynastyShingles = 313,
        MinecartTracks = 314,
        Coralstone = 315,
        BlueJellyfishJar = 316,
        GreenJellyfishJar = 317,
        PinkJellyfishJar = 318,
        ShipInABottle = 319,
        SeaweedPlanter = 320,
        BorealWood = 321,
        PalmWood = 322,
        PalmTree = 323,
        BeachPiles = 324,
        TinPlating = 325,
        Waterfall = 326,
        Lavafall = 327,
        Confetti = 328,
        MidnightConfetti = 329,
        CopperCoin = 330,
        SilverCoin = 331,
        GoldCoin = 332,
        PlatinumCoin = 333,
        WeaponRack = 334,
        FireworksBox = 335,
        LivingFire = 336,
        LetterStatues = 337,
        FireworkFountain = 338,
        GrasshopperCage = 339,
        LivingCursedFire = 340,
        LivingDemonFire = 341,
        LivingFrostFire = 342,
        LivingIchor = 343,
        LivingUltrabrightFire = 344,
        Honeyfall = 345,
        ChlorophyteBrick = 346,
        CrimtaneBrick = 347,
        ShroomitePlating = 348,
        MushroomStatue = 349,
        MartianConduitPlating = 350,
        Smoke = 351,
        CrimtaneThorn = 352,
        VineRope = 353,
        BewitchingTable = 354,
        AlchemyTable = 355,
        EnchantedSundial = 356,
        SmoothMarble = 357,
        GoldBirdCage = 358,
        GoldBunnyCage = 359,
        GoldButterflyJar = 360,
        GoldFrogCage = 361,
        GoldGrasshopperCage = 362,
        GoldMouseCage = 363,
        GoldWormCage = 364,
        SilkRope = 365,
        WebRope = 366,
        Marble = 367,
        Granite = 368,
        SmoothGranite = 369,
        MeteoriteBrick = 370,
        PinkSlime = 371,
        PeaceCandle = 372,
        MagicWaterDropper = 373,
        MagicLavaDropper = 374,
        MagicHoneyDropper = 375,
        Crates = 376,
        SharpeningStation = 377,
        TargetDummy = 378,
        Bubble = 379,
        PlanterBoxes = 380,
        FireMoss = 381,
        VineFlowers = 382,
        LivingMahogany = 383,
        MahoganyLeaf = 384,
        Crystal = 385,
        OpenTrapDoor = 386,
        ClosedTrapDoor = 387,
        ClosedTallGate = 388,
        OpenTallGate = 389,
        LavaLamp = 390,
        EnchantedNightcrawlerCage = 391,
        BuggyCage = 392,
        GrubbyCage = 393,
        SluggyCage = 394,
        ItemFrame = 395,
        Sandstone = 396,
        HardenedSand = 397,
        HardenedEbonsand = 398,
        HardenedCrimsand = 399,
        Ebonsandstone = 400,
        Crimsandstone = 401,
        HardenedPearlsand = 402,
        Pearlsandstone = 403,
        DesertFossil = 404,
        Fireplace = 405,
        Chimney = 406,
        SturdyFossil = 407,
        Luminite = 408,
        LuminiteBrick = 409,
        Monoliths = 410,
        Detonator = 411,
        AncientManipulator = 412,
        RedSquirrelCage = 413,
        GoldSquirrelCage = 414,
        SolarFragment = 415,
        VortexFragment = 416,
        NebulaFragment = 417,
        StardustFragment = 418,
        LogicGateLamps = 419,
        LogicGates = 420,
        ConveyorBeltClockwise = 421,
        ConveyorBeltCounterClockwise = 422,
        LogicSensors = 423,
        JunctionBox = 424,
        AnnouncementBox = 425,
        RedTeam = 426,
        RedTeamPlatform = 427,
        WeightedPressurePlates = 428,
        WireBulb = 429,
        GreenTeam = 430,
        BlueTeam = 431,
        YellowTeam = 432,
        PinkTeam = 433,
        WhiteTeam = 434,
        GreenTeamPlatform = 435,
        BlueTeamPlatform = 436,
        YellowTeamPlatform = 437,
        PinkTeamPlatform = 438,
        WhiteTeamPlatform = 439,
        GemLocks = 440,
        TrappedChests = 441,
        TealPressurePad = 442,
        Geyser = 443,
        Beehive = 444,
        PixelBox = 445,
        SillyPinkBalloon = 446,
        SillyPurpleBalloon = 447,
        SillyGreenBalloon = 448,
        BlueStreamer = 449,
        GreenStreamer = 450,
        PinkStreamer = 451,
        SillyBalloonMachine = 452,
        SillyTiedBalloons = 453,
        Pigronata = 454,
        PartyCenter = 455,
        SillyTiedBundleOfBalloons = 456,
        PartyPresent = 457,
        Sandfall = 458,
        Snowfall = 459,
        SnowCloud = 460,
        MagicSandDropper = 461,
        DesertSpiritLamp = 462,
        DefendersForge = 463,
        WarTable = 464,
        WarTableBanner = 465,
        EterniaCrystalStand = 466,
        Chests2 = 467,
        TrappedChests2 = 468,
        CrystalTable = 469
#pragma warning restore 1591
    }
    
    /// <summary>
    /// Provides extensions for the <see cref="BlockType"/> enumeration.
    /// </summary>
    public static class BlockTypeExtensions {
        private static readonly ISet<BlockType> _framesImportantBlockTypes = new HashSet<BlockType> {
            (BlockType)3,
            (BlockType)4,
            (BlockType)5,
            (BlockType)10,
            (BlockType)11,
            (BlockType)12,
            (BlockType)13,
            (BlockType)14,
            (BlockType)15,
            (BlockType)16,
            (BlockType)17,
            (BlockType)18,
            (BlockType)19,
            (BlockType)20,
            (BlockType)21,
            (BlockType)24,
            (BlockType)26,
            (BlockType)27,
            (BlockType)28,
            (BlockType)29,
            (BlockType)31,
            (BlockType)33,
            (BlockType)34,
            (BlockType)35,
            (BlockType)36,
            (BlockType)42,
            (BlockType)50,
            (BlockType)55,
            (BlockType)61,
            (BlockType)71,
            (BlockType)72,
            (BlockType)73,
            (BlockType)74,
            (BlockType)77,
            (BlockType)78,
            (BlockType)79,
            (BlockType)81,
            (BlockType)82,
            (BlockType)83,
            (BlockType)84,
            (BlockType)85,
            (BlockType)86,
            (BlockType)87,
            (BlockType)88,
            (BlockType)89,
            (BlockType)90,
            (BlockType)91,
            (BlockType)92,
            (BlockType)93,
            (BlockType)94,
            (BlockType)95,
            (BlockType)96,
            (BlockType)97,
            (BlockType)98,
            (BlockType)99,
            (BlockType)100,
            (BlockType)101,
            (BlockType)102,
            (BlockType)103,
            (BlockType)104,
            (BlockType)105,
            (BlockType)106,
            (BlockType)110,
            (BlockType)113,
            (BlockType)114,
            (BlockType)125,
            (BlockType)126,
            (BlockType)128,
            (BlockType)129,
            (BlockType)132,
            (BlockType)133,
            (BlockType)134,
            (BlockType)135,
            (BlockType)136,
            (BlockType)137,
            (BlockType)138,
            (BlockType)139,
            (BlockType)141,
            (BlockType)142,
            (BlockType)143,
            (BlockType)144,
            (BlockType)149,
            (BlockType)165,
            (BlockType)171,
            (BlockType)172,
            (BlockType)173,
            (BlockType)174,
            (BlockType)178,
            (BlockType)184,
            (BlockType)185,
            (BlockType)186,
            (BlockType)187,
            (BlockType)201,
            (BlockType)207,
            (BlockType)209,
            (BlockType)210,
            (BlockType)212,
            (BlockType)215,
            (BlockType)216,
            (BlockType)217,
            (BlockType)218,
            (BlockType)219,
            (BlockType)220,
            (BlockType)227,
            (BlockType)228,
            (BlockType)231,
            (BlockType)233,
            (BlockType)235,
            (BlockType)236,
            (BlockType)237,
            (BlockType)238,
            (BlockType)239,
            (BlockType)240,
            (BlockType)241,
            (BlockType)242,
            (BlockType)243,
            (BlockType)244,
            (BlockType)245,
            (BlockType)246,
            (BlockType)247,
            (BlockType)254,
            (BlockType)269,
            (BlockType)270,
            (BlockType)271,
            (BlockType)275,
            (BlockType)276,
            (BlockType)277,
            (BlockType)278,
            (BlockType)279,
            (BlockType)280,
            (BlockType)281,
            (BlockType)282,
            (BlockType)283,
            (BlockType)285,
            (BlockType)286,
            (BlockType)287,
            (BlockType)288,
            (BlockType)289,
            (BlockType)290,
            (BlockType)291,
            (BlockType)292,
            (BlockType)293,
            (BlockType)294,
            (BlockType)295,
            (BlockType)296,
            (BlockType)297,
            (BlockType)298,
            (BlockType)299,
            (BlockType)300,
            (BlockType)301,
            (BlockType)302,
            (BlockType)303,
            (BlockType)304,
            (BlockType)305,
            (BlockType)306,
            (BlockType)307,
            (BlockType)308,
            (BlockType)309,
            (BlockType)310,
            (BlockType)314,
            (BlockType)316,
            (BlockType)317,
            (BlockType)318,
            (BlockType)319,
            (BlockType)320,
            (BlockType)323,
            (BlockType)324,
            (BlockType)334,
            (BlockType)335,
            (BlockType)337,
            (BlockType)338,
            (BlockType)339,
            (BlockType)349,
            (BlockType)354,
            (BlockType)355,
            (BlockType)356,
            (BlockType)358,
            (BlockType)359,
            (BlockType)360,
            (BlockType)361,
            (BlockType)362,
            (BlockType)363,
            (BlockType)364,
            (BlockType)372,
            (BlockType)373,
            (BlockType)374,
            (BlockType)375,
            (BlockType)376,
            (BlockType)377,
            (BlockType)378,
            (BlockType)380,
            (BlockType)386,
            (BlockType)387,
            (BlockType)388,
            (BlockType)389,
            (BlockType)390,
            (BlockType)391,
            (BlockType)392,
            (BlockType)393,
            (BlockType)394,
            (BlockType)395,
            (BlockType)405,
            (BlockType)406,
            (BlockType)410,
            (BlockType)411,
            (BlockType)412,
            (BlockType)413,
            (BlockType)414,
            (BlockType)419,
            (BlockType)420,
            (BlockType)423,
            (BlockType)424,
            (BlockType)425,
            (BlockType)427,
            (BlockType)428,
            (BlockType)429,
            (BlockType)435,
            (BlockType)436,
            (BlockType)437,
            (BlockType)438,
            (BlockType)439,
            (BlockType)440,
            (BlockType)441,
            (BlockType)442,
            (BlockType)443,
            (BlockType)444,
            (BlockType)445,
            (BlockType)452,
            (BlockType)453,
            (BlockType)454,
            (BlockType)455,
            (BlockType)456,
            (BlockType)457,
            (BlockType)461,
            (BlockType)462,
            (BlockType)463,
            (BlockType)464,
            (BlockType)465,
            (BlockType)466,
            (BlockType)467,
            (BlockType)468,
            (BlockType)469
        };

        /// <summary>
        /// Returns a value indicating whether frames are important for the block <paramref name="type"/>.
        /// </summary>
        /// <param name="type">The block type.</param>
        /// <returns><see langword="true"/> if frames are important; otherwise, <see langword="false"/>.</returns>
        [Pure]
        public static bool AreFramesImportant(this BlockType type) => _framesImportantBlockTypes.Contains(type);
    }
}
