using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Orion.Exceptions
{  
	/// <summary>UserHandlerException - An exception generated by the user handler.</summary>
	[Serializable]
	public class GroupNotFoundException : Exception
	{
		/// <summary>Creates a new UserHandlerException object.</summary>
		/// <param name="message">The message for the object.</param>
		/// <returns>A new UserHandlerException object.</returns>
		public GroupNotFoundException(string groupname)
			: base(String.Format(Strings.GroupNotFound, groupname))
		{
		}
	}

	[Serializable]
	public class SetUserGroupException : ArgumentException
	{
		public SetUserGroupException(string exception, string parameter)
			:base(exception, parameter)
		{

		}
	}
}
