// Copyright (c) 2015-2019 Pryaxis & Orion Contributors
// 
// This file is part of Orion.
// 
// Orion is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Orion is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Orion.  If not, see <https://www.gnu.org/licenses/>.

using JetBrains.Annotations;

namespace Orion.Entities {
    /// <summary>
    /// Specifies an emote type.
    /// </summary>
    [PublicAPI]
    public enum EmoteType : short {
#pragma warning disable 1591
        NpcHead = -1,
        Love = 0,
        Anger = 1,
        Cry = 2,
        Alert = 3,
        Rain = 4,
        Lightning = 5,
        Rainbow = 6,
        Ring = 7,
        Poison = 8,
        Burn = 9,
        Silenced = 10,
        Cursed = 11,
        Bee = 12,
        Slime = 13,
        Tree = 14,
        Laugh = 15,
        Fear = 16,
        Note = 17,
        BloodMoon = 18,
        Eclipse = 19,
        PumpkinMoon = 20,
        SnowMoon = 21,
        SkyBiome = 22,
        OtherworldBiome = 23,
        JungleBiome = 24,
        CrimsonBiome = 25,
        CorruptionBiome = 26,
        HallowedBiome = 27,
        DesertBiome = 28,
        BeachBiome = 29,
        RockLayer = 30,
        LavaLayer = 31,
        SnowBiome = 32,
        ScissorsWin = 33,
        RockWin = 34,
        PaperWin = 35,
        Scissors = 36,
        Rock = 37,
        Paper = 38,
        EyeOfCthulhu = 39,
        EaterOfWorlds = 40,
        BrainOfCthulhu = 41,
        QueenBee = 42,
        Skeletron = 43,
        WallOfFlesh = 44,
        Destroyer = 45,
        SkeletronPrime = 46,
        TheTwins = 47,
        Plantera = 48,
        Golem = 49,
        DukeFishron = 50,
        KingSlime = 51,
        LunaticCultist = 52,
        MoonLord = 53,
        MourningWood = 54,
        Pumpking = 55,
        Everscream = 56,
        IceQueen = 57,
        SantaNk1 = 58,
        FlyingDutchman = 59,
        MartianSaucer = 60,
        Zombie = 61,
        Bunny = 62,
        Butterfly = 63,
        Goblin = 64,
        PirateEnemy = 65,
        Snowman = 66,
        Spider = 67,
        Bird = 68,
        Mouse = 69,
        Goldfish = 70,
        Martian = 71,
        Skeleton = 72,
        LifePotion = 73,
        ManaPotion = 74,
        Soup = 75,
        CookedFish = 76,
        Ale = 77,
        Sword = 78,
        FishingRod = 79,
        BugNet = 80,
        Dynamite = 81,
        Minishark = 82,
        Cog = 83,
        Tombstone = 84,
        Goldpile = 85,
        DiamondRing = 86,
        Confused = 87,
        Kiss = 88,
        Sleep = 89,
        Pickaxe = 90,
        Run = 91,
        Kick = 92,
        Fight = 93,
        Eating = 94,
        Sunny = 95,
        Cloudy = 96,
        Storming = 97,
        Snowstorm = 98,
        Meteor = 99,
        Fire = 100,
        Merchant = 101,
        Nurse = 102,
        ArmsDealer = 103,
        Dryad = 104,
        Guide = 105,
        Oldman = 106,
        Demolitionist = 107,
        Clothier = 108,
        GoblinTinkerer = 109,
        Wizard = 110,
        Mechanic = 111,
        Santa = 112,
        Truffle = 113,
        Steampunker = 114,
        DyeTrader = 115,
        PartyGirl = 116,
        Cyborg = 117,
        Painter = 118,
        WitchDoctor = 119,
        Pirate = 120,
        Stylist = 121,
        TravellingMerchant = 122,
        Angler = 123,
        SkeletonMerchant = 124,
        TaxCollector = 125,
        PartyPresent = 126,
        PartyBalloons = 127,
        PartyCake = 128,
        PartyHats = 129,
        Tavernkeep = 130,
        Beer = 131,
        DefenderMedal = 132,
        OldOnesArmy = 133
#pragma warning restore 1591
    }
}
