// Copyright (c) 2020 Pryaxis & Orion Contributors
// 
// This file is part of Orion.
// 
// Orion is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Orion is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Orion.  If not, see <https://www.gnu.org/licenses/>.

using System.Collections.Generic;
using System.Diagnostics.Contracts;

namespace Orion.Core.World.Tiles
{
    /// <summary>
    /// Specifies a block ID.
    /// </summary>
    public enum BlockId : ushort
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        Dirt = 0,
        Stone = 1,
        Grass = 2,
        ShortGrassPlants = 3,
        Torches = 4,
        Trees = 5,
        IronOre = 6,
        CopperOre = 7,
        GoldOre = 8,
        SilverOre = 9,
        ClosedDoors = 10,
        OpenDoors = 11,
        CrystalHeart = 12,
        Bottles = 13,
        Tables = 14,
        Chairs = 15,
        Anvils = 16,
        Furnace = 17,
        WorkBenches = 18,
        Platforms = 19,
        Acorn = 20,
        Chests = 21,
        DemoniteOre = 22,
        CorruptGrass = 23,
        ShortCorruptGrassPlants = 24,
        Ebonstone = 25,
        EvilAltars = 26,
        Sunflower = 27,
        Pots = 28,
        PiggyBank = 29,
        Wood = 30,
        EvilOrbs = 31,
        CorruptThornyBush = 32,
        Candles = 33,
        Chandeliers = 34,
        JackOLantern = 35,
        Present = 36,
        Meteorite = 37,
        GrayBrick = 38,
        RedBrick = 39,
        Clay = 40,
        BlueBrick = 41,
        Lanterns = 42,
        GreenBrick = 43,
        PinkBrick = 44,
        GoldBrick = 45,
        SilverBrick = 46,
        CopperBrick = 47,
        Spike = 48,
        WaterCandle = 49,
        Book = 50,
        Cobweb = 51,
        GrassVines = 52,
        Sand = 53,
        Glass = 54,
        Sign = 55,
        Obsidian = 56,
        Ash = 57,
        Hellstone = 58,
        Mud = 59,
        JungleGrass = 60,
        ShortJungleGrassPlants = 61,
        JungleGrassVines = 62,
        SapphireStone = 63,
        RubyStone = 64,
        EmeraldStone = 65,
        TopazStone = 66,
        AmethystStone = 67,
        DiamondStone = 68,
        JungleThornyBush = 69,
        MushroomGrass = 70,
        MushroomGrassPlants = 71,
        MushroomTrees = 72,
        TallGrassPlants = 73,
        TallJungleGrassPlants = 74,
        ObsidianBrick = 75,
        HellstoneBrick = 76,
        Hellforge = 77,
        ClayPot = 78,
        Beds = 79,
        CactusPlant = 80,
        Coral = 81,
        ImmatureHerbs = 82,
        MatureHerbs = 83,
        BloomingHerbs = 84,
        Tombstones = 85,
        Loom = 86,
        Pianos = 87,
        Dressers = 88,
        Benches = 89,
        Bathtubs = 90,
        Banners = 91,
        LampPost = 92,
        Lamps = 93,
        Keg = 94,
        ChineseLantern = 95,
        CookingPots = 96,
        Safe = 97,
        SkullLantern = 98,
        TrashCan = 99,
        Candelabras = 100,
        Bookcases = 101,
        Throne = 102,
        Bowls = 103,
        Clocks = 104,
        Statues = 105,
        Sawmill = 106,
        CobaltOre = 107,
        MythrilOre = 108,
        HallowedGrass = 109,
        ShortHallowedGrassPlants = 110,
        AdamantiteOre = 111,
        Ebonsand = 112,
        TallHallowedGrassPlants = 113,
        TinkerersWorkshop = 114,
        HallowedGrassVines = 115,
        Pearlsand = 116,
        Pearlstone = 117,
        PearlstoneBrick = 118,
        IridescentBrick = 119,
        MudstoneBrick = 120,
        CobaltBrick = 121,
        MythrilBrick = 122,
        Silt = 123,
        WoodenBeam = 124,
        CrystalBall = 125,
        DiscoBall = 126,
        IceRod = 127,
        Mannequin = 128,
        CrystalShard = 129,
        ActiveStone = 130,
        InactiveStone = 131,
        Lever = 132,
        HardmodeForges = 133,
        HardmodeAnvils = 134,
        PressurePlates = 135,
        Switch = 136,
        Traps = 137,
        Boulder = 138,
        MusicBoxes = 139,
        DemoniteBrick = 140,
        Explosives = 141,
        InletPump = 142,
        OutletPump = 143,
        Timers = 144,
        CandyCane = 145,
        GreenCandyCane = 146,
        Snow = 147,
        SnowBrick = 148,
        HolidayLights = 149,
        AdamantiteBeam = 150,
        SandstoneBrick = 151,
        EbonstoneBrick = 152,
        RedStucco = 153,
        YellowStucco = 154,
        GreenStucco = 155,
        GrayStucco = 156,
        Ebonwood = 157,
        RichMahogany = 158,
        Pearlwood = 159,
        RainbowBrick = 160,
        Ice = 161,
        ThinIce = 162,
        PurpleIce = 163,
        PinkIce = 164,
        AmbientObjects = 165,
        TinOre = 166,
        LeadOre = 167,
        TungstenOre = 168,
        PlatinumOre = 169,
        PineTree = 170,
        ChristmasTree = 171,
        Sinks = 172,
        PlatinumCandelabra = 173,
        PlatinumCandle = 174,
        TinBrick = 175,
        TungstenBrick = 176,
        PlatinumBrick = 177,
        Gems = 178,
        GreenMoss = 179,
        BrownMoss = 180,
        RedMoss = 181,
        BlueMoss = 182,
        PurpleMoss = 183,
        MossPlants = 184,
        SmallAmbientObjects = 185,
        LargeAmbientObjects = 186,
        LargeAmbientObjects2 = 187,
        Cactus = 188,
        Cloud = 189,
        GlowingMushroom = 190,
        LivingWood = 191,
        Leaf = 192,
        Slime = 193,
        Bone = 194,
        Flesh = 195,
        RainCloud = 196,
        FrozenSlime = 197,
        Asphalt = 198,
        CrimsonGrass = 199,
        RedIce = 200,
        ShortCrimsonGrassPlants = 201,
        Sunplate = 202,
        Crimstone = 203,
        CrimtaneOre = 204,
        CrimsonGrassVines = 205,
        IceBrick = 206,
        WaterFountains = 207,
        Shadewood = 208,
        Cannons = 209,
        LandMine = 210,
        ChlorophyteOre = 211,
        SnowballLauncher = 212,
        Rope = 213,
        Chain = 214,
        Campfires = 215,
        Fireworks = 216,
        BlendOMatic = 217,
        MeatGrinder = 218,
        Extractinator = 219,
        Solidifier = 220,
        PalladiumOre = 221,
        OrichalcumOre = 222,
        TitaniumOre = 223,
        Slush = 224,
        Hive = 225,
        LihzahrdBrick = 226,
        DyePlants = 227,
        DyeVat = 228,
        Honey = 229,
        CrispyHoney = 230,
        QueenBeeLarva = 231,
        WoodenSpike = 232,
        PlantDetritus = 233,
        Crimsand = 234,
        Teleporter = 235,
        LifeFruit = 236,
        LihzahrdAltar = 237,
        PlanteraBulb = 238,
        MetalBars = 239,
        Paintings3x3 = 240,
        Paintings4x3 = 241,
        Paintings6x4 = 242,
        ImbuingStation = 243,
        BubbleMachine = 244,
        Paintings2x3 = 245,
        Paintings3x2 = 246,
        Autohammer = 247,
        PalladiumColumn = 248,
        Bubblegum = 249,
        Titanstone = 250,
        Pumpkin = 251,
        Hay = 252,
        SpookyWood = 253,
        PumpkinSeed = 254,
        OfflineAmethystGemspark = 255,
        OfflineTopazGemspark = 256,
        OfflineSapphireGemspark = 257,
        OfflineEmeraldGemspark = 258,
        OfflineRubyGemspark = 259,
        OfflineDiamondGemspark = 260,
        OfflineAmberGemspark = 261,
        AmethystGemspark = 262,
        TopazGemspark = 263,
        SapphireGemspark = 264,
        EmeraldGemspark = 265,
        RubyGemspark = 266,
        DiamondGemspark = 267,
        AmberGemspark = 268,
        Womannequin = 269,
        FireflyInABottle = 270,
        LightningBugInABottle = 271,
        Cog = 272,
        StoneSlab = 273,
        SandstoneSlab = 274,
        BunnyCage = 275,
        SquirrelCage = 276,
        MallardDuckCage = 277,
        DuckCage = 278,
        BirdCage = 279,
        BlueJayCage = 280,
        CardinalCage = 281,
        FishBowl = 282,
        HeavyWorkBench = 283,
        CopperPlating = 284,
        SnailCage = 285,
        GlowingSnailCage = 286,
        AmmoBox = 287,
        MonarchButterflyJar = 288,
        PurpleEmperorButterflyJar = 289,
        RedAdmiralButterflyJar = 290,
        UlyssesButterflyJar = 291,
        SulphurButterflyJar = 292,
        TreeNymphButterflyJar = 293,
        ZebraSwallowtailButterflyJar = 294,
        JuliaButterflyJar = 295,
        ScorpionCage = 296,
        BlackScorpionCage = 297,
        FrogCage = 298,
        MouseCage = 299,
        BoneWelder = 300,
        FleshCloningVat = 301,
        GlassKiln = 302,
        LihzahrdFurnace = 303,
        LivingLoom = 304,
        SkyMill = 305,
        IceMachine = 306,
        SteampunkBoiler = 307,
        HoneyDispenser = 308,
        PenguinCage = 309,
        WormCage = 310,
        DynastyWood = 311,
        RedDynastyShingles = 312,
        BlueDynastyShingles = 313,
        Tracks = 314,
        Coralstone = 315,
        BlueJellyfishJar = 316,
        GreenJellyfishJar = 317,
        PinkJellyfishJar = 318,
        ShipInABottle = 319,
        SeaweedPlanter = 320,
        BorealWood = 321,
        PalmWood = 322,
        PalmTree = 323,
        Seashells = 324,
        TinPlating = 325,
        Waterfall = 326,
        Lavafall = 327,
        Confetti = 328,
        MidnightConfetti = 329,
        CopperCoin = 330,
        SilverCoin = 331,
        GoldCoin = 332,
        PlatinumCoin = 333,
        Racks = 334,
        FireworksBox = 335,
        LivingFire = 336,
        TextStatues = 337,
        FireworkFountain = 338,
        GrasshopperCage = 339,
        LivingCursedFire = 340,
        LivingDemonFire = 341,
        LivingFrostFire = 342,
        LivingIchor = 343,
        LivingUltrabrightFire = 344,
        Honeyfall = 345,
        ChlorophyteBrick = 346,
        CrimtaneBrick = 347,
        ShroomitePlating = 348,
        MushroomStatue = 349,
        MartianConduitPlating = 350,
        Smoke = 351,
        CrimsonThornyBush = 352,
        VineRope = 353,
        BewitchingTable = 354,
        AlchemyTable = 355,
        EnchantedSundial = 356,
        SmoothMarble = 357,
        GoldBirdCage = 358,
        GoldBunnyCage = 359,
        GoldButterflyJar = 360,
        GoldFrogCage = 361,
        GoldGrasshopperCage = 362,
        GoldMouseCage = 363,
        GoldWormCage = 364,
        SilkRope = 365,
        WebRope = 366,
        Marble = 367,
        Granite = 368,
        SmoothGranite = 369,
        MeteoriteBrick = 370,
        PinkSlime = 371,
        PeaceCandle = 372,
        MagicWaterDropper = 373,
        MagicLavaDropper = 374,
        MagicHoneyDropper = 375,
        Crates = 376,
        SharpeningStation = 377,
        TargetDummy = 378,
        Bubble = 379,
        PlanterBoxes = 380,
        LavaMoss = 381,
        GrassVineFlowers = 382,
        LivingMahogany = 383,
        MahoganyLeaf = 384,
        Crystal = 385,
        OpenTrapDoor = 386,
        ClosedTrapDoor = 387,
        ClosedTallGate = 388,
        OpenTallGate = 389,
        LavaLamp = 390,
        EnchantedNightcrawlerCage = 391,
        BuggyCage = 392,
        GrubbyCage = 393,
        SluggyCage = 394,
        ItemFrame = 395,
        Sandstone = 396,
        HardenedSand = 397,
        HardenedEbonsand = 398,
        HardenedCrimsand = 399,
        Ebonsandstone = 400,
        Crimsandstone = 401,
        HardenedPearlsand = 402,
        Pearlsandstone = 403,
        DesertFossil = 404,
        Fireplace = 405,
        Chimney = 406,
        SturdyFossil = 407,
        Luminite = 408,
        LuminiteBrick = 409,
        Monoliths = 410,
        Detonator = 411,
        AncientManipulator = 412,
        RedSquirrelCage = 413,
        GoldSquirrelCage = 414,
        SolarFragment = 415,
        VortexFragment = 416,
        NebulaFragment = 417,
        StardustFragment = 418,
        LogicGateLamps = 419,
        LogicGates = 420,
        ConveyorBeltClockwise = 421,
        ConveyorBeltCounterClockwise = 422,
        LogicSensors = 423,
        JunctionBox = 424,
        AnnouncementBox = 425,
        RedTeam = 426,
        RedTeamPlatform = 427,
        WeightedPressurePlates = 428,
        WireBulb = 429,
        GreenTeam = 430,
        BlueTeam = 431,
        YellowTeam = 432,
        PinkTeam = 433,
        WhiteTeam = 434,
        GreenTeamPlatform = 435,
        BlueTeamPlatform = 436,
        YellowTeamPlatform = 437,
        PinkTeamPlatform = 438,
        WhiteTeamPlatform = 439,
        GemLocks = 440,
        TrappedChests = 441,
        TealPressurePad = 442,
        Geyser = 443,
        Beehive = 444,
        PixelBox = 445,
        SillyPinkBalloon = 446,
        SillyPurpleBalloon = 447,
        SillyGreenBalloon = 448,
        BlueStreamer = 449,
        GreenStreamer = 450,
        PinkStreamer = 451,
        SillyBalloonMachine = 452,
        SillyTiedBalloons = 453,
        Pigronata = 454,
        PartyCenter = 455,
        SillyTiedBundleOfBalloons = 456,
        PartyPresent = 457,
        Sandfall = 458,
        Snowfall = 459,
        SnowCloud = 460,
        MagicSandDropper = 461,
        DesertSpiritLamp = 462,
        DefendersForge = 463,
        WarTable = 464,
        WarTableBanner = 465,
        EterniaCrystalStand = 466,
        Chests2 = 467,
        FakeChests2 = 468,
        Tables2 = 469,
        Mannequins = 470,
        WeaponRack = 471,
        IronBrick = 472,
        LeadBrick = 473,
        Lesion = 474,
        HatRack = 475,
        GolfCup = 476,
        GolfGrass = 477,
        CrimstoneBrick = 478,
        SmoothSandstone = 479,
        BloodMoonMonolith = 480,
        CrackedBlueBrick = 481,
        CrackedGreenBrick = 482,
        CrackedPinkBrick = 483,
        RollingCactus = 484,
        AntlionLarva = 485,
        DrumSet = 486,
        PicnicTables = 487,
        FallenLogs = 488,
        PinWheel = 489,
        WeatherVane = 490,
        VoidVault = 491,
        HallowedGolfGrass = 492,
        GolfCupFlag = 493,
        GolfTee = 494,
        ShellPile = 495,
        AntiPortal = 496,
        Toilets = 497,
        SpiderNest = 498,
        DecayChamber = 499,
        SolarBrick = 500,
        VortexBrick = 501,
        NebulaBrick = 502,
        StardustBrick = 503,
        SnakeRope = 504,
        GoldFishBowl = 505,
        BastStatue = 506,
        GoldStarry = 507,
        BlueStarry = 508,
        VoidMonolith = 509,
        ArrowSign = 510,
        PaintedArrowSign = 511,
        GreenMossBrick = 512,
        BrownMossBrick = 513,
        RedMossBrick = 514,
        BlueMossBrick = 515,
        PurpleMossBrick = 516,
        LavaMossBrick = 517,
        LilyPad = 518,
        Cattail = 519,
        Plate = 520,
        BlackDragonflyJar = 521,
        BlueDragonflyJar = 522,
        GreenDragonflyJar = 523,
        OrangeDragonflyJar = 524,
        RedDragonflyJar = 525,
        YellowDragonflyJar = 526,
        GoldDragonflyJar = 527,
        MushroomGrassVines = 528,
        SeaOats = 529,
        OasisPlants = 530,
        BoulderStatue = 531,
        MaggotCage = 532,
        RatCage = 533,
        KryptonMoss = 534,
        KryptonMossBrick = 535,
        XenonMoss = 536,
        XenonMossBrick = 537,
        LadybugCage = 538,
        ArgonMoss = 539,
        ArgonMossBrick = 540,
        Echo = 541,
        OwlCage = 542,
        PupfishBowl = 543,
        GoldLadybugCage = 544,
        LawnFlamingo = 545,
        Grate = 546,
        PottedPlants = 547,
        PottedPlants2 = 548,
        Seaweed = 549,
        TurtleCage = 550,
        JungleTurtleCage = 551,
        Sandcastles = 552,
        GrebeCage = 553,
        SeagullCage = 554,
        WaterStriderCage = 555,
        GoldWaterStriderCage = 556,
        ClosedGrate = 557,
        SeahorseCage = 558,
        GoldSeahorseCage = 559,
        GolfTrophies = 560,
        MarbleColumn = 561,
        Bamboo = 562,
        LargeBamboo = 563,
        PlasmaLamp = 564,
        FogMachine = 565,
        AmberStone = 566,
        GardenGnome = 567,
        PinkFairyJar = 568,
        GreenFairyJar = 569,
        BlueFairyJar = 570,
        BambooPlant = 571,
        SoulInABottles = 572,
        TatteredWoodSign = 573,
        BorealBeam = 574,
        RichMahoganyBeam = 575,
        GraniteColumn = 576,
        SandstoneColumn = 577,
        MushroomBeam = 578,
        RockGolemHead = 579,
        HellButterflyJar = 580,
        LavaflyInABottle = 581,
        MagmaSnailCage = 582,
        TopazTree = 583,
        AmethystTree = 584,
        SapphireTree = 585,
        EmeraldTree = 586,
        RubyTree = 587,
        DiamondTree = 588,
        AmberTree = 589,
        GemSaplings = 590,
        HangingPots = 591,
        HangingBrazier = 592,
        MiniVolcano = 593,
        LargeVolcano = 594,
        SakuraSapling = 595,
        SakuraTree = 596,
        TeleportationPylons = 597,
        LavaSerpentBowl = 598,
        AmethystBunnyCage = 599,
        TopazBunnyCage = 600,
        SapphireBunnyCage = 601,
        EmeraldBunnyCage = 602,
        RubyBunnyCage = 603,
        DiamondBunnyCage = 604,
        AmberBunnyCage = 605,
        AmethystSquirrelCage = 606,
        TopazSquirrelCage = 607,
        SapphireSquirrelCage = 608,
        EmeraldSquirrelCage = 609,
        RubySquirrelCage = 610,
        DiamondSquirrelCage = 611,
        AmberSquirrelCage = 612,
        PottedLavaPlants = 613,
        PottedEmberTendrils = 614,
        YellowWillowSapling = 615,
        YellowWillowTree = 616,
        BossRelics = 617,
        StoneAccentSlab = 618,
        TruffleWormCage = 619,
        PrismaticLacewingJar = 620,
        SliceOfCake = 621,
        Teapot = 622
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    }

    /// <summary>
    /// Provides extensions for the <see cref="BlockId"/> enumeration.
    /// </summary>
    public static class BlockIdExtensions
    {
        private static readonly ISet<BlockId> _frames = new HashSet<BlockId> {
            BlockId.ShortGrassPlants,
            BlockId.Torches,
            BlockId.Trees,
            BlockId.ClosedDoors,
            BlockId.OpenDoors,
            BlockId.CrystalHeart,
            BlockId.Bottles,
            BlockId.Tables,
            BlockId.Chairs,
            BlockId.Anvils,
            BlockId.Furnace,
            BlockId.WorkBenches,
            BlockId.Platforms,
            BlockId.Acorn,
            BlockId.Chests,
            BlockId.ShortCorruptGrassPlants,
            BlockId.EvilAltars,
            BlockId.Sunflower,
            BlockId.Pots,
            BlockId.PiggyBank,
            BlockId.EvilOrbs,
            BlockId.Candles,
            BlockId.Chandeliers,
            BlockId.JackOLantern,
            BlockId.Present,
            BlockId.Lanterns,
            BlockId.WaterCandle,
            BlockId.Book,
            BlockId.Sign,
            BlockId.ShortJungleGrassPlants,
            BlockId.MushroomGrassPlants,
            BlockId.MushroomTrees,
            BlockId.TallGrassPlants,
            BlockId.TallJungleGrassPlants,
            BlockId.Hellforge,
            BlockId.ClayPot,
            BlockId.Beds,
            BlockId.Coral,
            BlockId.ImmatureHerbs,
            BlockId.MatureHerbs,
            BlockId.BloomingHerbs,
            BlockId.Tombstones,
            BlockId.Loom,
            BlockId.Pianos,
            BlockId.Dressers,
            BlockId.Benches,
            BlockId.Bathtubs,
            BlockId.Banners,
            BlockId.LampPost,
            BlockId.Lamps,
            BlockId.Keg,
            BlockId.ChineseLantern,
            BlockId.CookingPots,
            BlockId.Safe,
            BlockId.SkullLantern,
            BlockId.TrashCan,
            BlockId.Candelabras,
            BlockId.Bookcases,
            BlockId.Throne,
            BlockId.Bowls,
            BlockId.Clocks,
            BlockId.Statues,
            BlockId.Sawmill,
            BlockId.ShortHallowedGrassPlants,
            BlockId.TallHallowedGrassPlants,
            BlockId.TinkerersWorkshop,
            BlockId.CrystalBall,
            BlockId.DiscoBall,
            BlockId.Mannequin,
            BlockId.CrystalShard,
            BlockId.Lever,
            BlockId.HardmodeForges,
            BlockId.HardmodeAnvils,
            BlockId.PressurePlates,
            BlockId.Switch,
            BlockId.Traps,
            BlockId.Boulder,
            BlockId.MusicBoxes,
            BlockId.Explosives,
            BlockId.InletPump,
            BlockId.OutletPump,
            BlockId.Timers,
            BlockId.HolidayLights,
            BlockId.AmbientObjects,
            BlockId.ChristmasTree,
            BlockId.Sinks,
            BlockId.PlatinumCandelabra,
            BlockId.PlatinumCandle,
            BlockId.Gems,
            BlockId.MossPlants,
            BlockId.SmallAmbientObjects,
            BlockId.LargeAmbientObjects,
            BlockId.LargeAmbientObjects2,
            BlockId.ShortCrimsonGrassPlants,
            BlockId.WaterFountains,
            BlockId.Cannons,
            BlockId.LandMine,
            BlockId.SnowballLauncher,
            BlockId.Campfires,
            BlockId.Fireworks,
            BlockId.BlendOMatic,
            BlockId.MeatGrinder,
            BlockId.Extractinator,
            BlockId.Solidifier,
            BlockId.DyePlants,
            BlockId.DyeVat,
            BlockId.QueenBeeLarva,
            BlockId.PlantDetritus,
            BlockId.Teleporter,
            BlockId.LifeFruit,
            BlockId.LihzahrdAltar,
            BlockId.PlanteraBulb,
            BlockId.MetalBars,
            BlockId.Paintings3x3,
            BlockId.Paintings4x3,
            BlockId.Paintings6x4,
            BlockId.ImbuingStation,
            BlockId.BubbleMachine,
            BlockId.Paintings2x3,
            BlockId.Paintings3x2,
            BlockId.Autohammer,
            BlockId.PumpkinSeed,
            BlockId.Womannequin,
            BlockId.FireflyInABottle,
            BlockId.LightningBugInABottle,
            BlockId.BunnyCage,
            BlockId.SquirrelCage,
            BlockId.MallardDuckCage,
            BlockId.DuckCage,
            BlockId.BirdCage,
            BlockId.BlueJayCage,
            BlockId.CardinalCage,
            BlockId.FishBowl,
            BlockId.HeavyWorkBench,
            BlockId.SnailCage,
            BlockId.GlowingSnailCage,
            BlockId.AmmoBox,
            BlockId.MonarchButterflyJar,
            BlockId.PurpleEmperorButterflyJar,
            BlockId.RedAdmiralButterflyJar,
            BlockId.UlyssesButterflyJar,
            BlockId.SulphurButterflyJar,
            BlockId.TreeNymphButterflyJar,
            BlockId.ZebraSwallowtailButterflyJar,
            BlockId.JuliaButterflyJar,
            BlockId.ScorpionCage,
            BlockId.BlackScorpionCage,
            BlockId.FrogCage,
            BlockId.MouseCage,
            BlockId.BoneWelder,
            BlockId.FleshCloningVat,
            BlockId.GlassKiln,
            BlockId.LihzahrdFurnace,
            BlockId.LivingLoom,
            BlockId.SkyMill,
            BlockId.IceMachine,
            BlockId.SteampunkBoiler,
            BlockId.HoneyDispenser,
            BlockId.PenguinCage,
            BlockId.WormCage,
            BlockId.Tracks,
            BlockId.BlueJellyfishJar,
            BlockId.GreenJellyfishJar,
            BlockId.PinkJellyfishJar,
            BlockId.ShipInABottle,
            BlockId.SeaweedPlanter,
            BlockId.PalmTree,
            BlockId.Seashells,
            BlockId.Racks,
            BlockId.FireworksBox,
            BlockId.TextStatues,
            BlockId.FireworkFountain,
            BlockId.GrasshopperCage,
            BlockId.MushroomStatue,
            BlockId.BewitchingTable,
            BlockId.AlchemyTable,
            BlockId.EnchantedSundial,
            BlockId.GoldBirdCage,
            BlockId.GoldBunnyCage,
            BlockId.GoldButterflyJar,
            BlockId.GoldFrogCage,
            BlockId.GoldGrasshopperCage,
            BlockId.GoldMouseCage,
            BlockId.GoldWormCage,
            BlockId.PeaceCandle,
            BlockId.MagicWaterDropper,
            BlockId.MagicLavaDropper,
            BlockId.MagicHoneyDropper,
            BlockId.Crates,
            BlockId.SharpeningStation,
            BlockId.TargetDummy,
            BlockId.PlanterBoxes,
            BlockId.OpenTrapDoor,
            BlockId.ClosedTrapDoor,
            BlockId.ClosedTallGate,
            BlockId.OpenTallGate,
            BlockId.LavaLamp,
            BlockId.EnchantedNightcrawlerCage,
            BlockId.BuggyCage,
            BlockId.GrubbyCage,
            BlockId.SluggyCage,
            BlockId.ItemFrame,
            BlockId.Fireplace,
            BlockId.Chimney,
            BlockId.Monoliths,
            BlockId.Detonator,
            BlockId.AncientManipulator,
            BlockId.RedSquirrelCage,
            BlockId.GoldSquirrelCage,
            BlockId.LogicGateLamps,
            BlockId.LogicGates,
            BlockId.LogicSensors,
            BlockId.JunctionBox,
            BlockId.AnnouncementBox,
            BlockId.RedTeamPlatform,
            BlockId.WeightedPressurePlates,
            BlockId.WireBulb,
            BlockId.GreenTeamPlatform,
            BlockId.BlueTeamPlatform,
            BlockId.YellowTeamPlatform,
            BlockId.PinkTeamPlatform,
            BlockId.WhiteTeamPlatform,
            BlockId.GemLocks,
            BlockId.TrappedChests,
            BlockId.TealPressurePad,
            BlockId.Geyser,
            BlockId.Beehive,
            BlockId.PixelBox,
            BlockId.SillyBalloonMachine,
            BlockId.SillyTiedBalloons,
            BlockId.Pigronata,
            BlockId.PartyCenter,
            BlockId.SillyTiedBundleOfBalloons,
            BlockId.PartyPresent,
            BlockId.MagicSandDropper,
            BlockId.DesertSpiritLamp,
            BlockId.DefendersForge,
            BlockId.WarTable,
            BlockId.WarTableBanner,
            BlockId.EterniaCrystalStand,
            BlockId.Chests2,
            BlockId.FakeChests2,
            BlockId.Tables2,
            BlockId.Mannequins,
            BlockId.WeaponRack,
            BlockId.HatRack,
            BlockId.GolfCup,
            BlockId.BloodMoonMonolith,
            BlockId.RollingCactus,
            BlockId.AntlionLarva,
            BlockId.DrumSet,
            BlockId.PicnicTables,
            BlockId.FallenLogs,
            BlockId.PinWheel,
            BlockId.WeatherVane,
            BlockId.VoidVault,
            BlockId.GolfCupFlag,
            BlockId.GolfTee,
            BlockId.Toilets,
            BlockId.DecayChamber,
            BlockId.GoldFishBowl,
            BlockId.BastStatue,
            BlockId.VoidMonolith,
            BlockId.ArrowSign,
            BlockId.PaintedArrowSign,
            BlockId.LilyPad,
            BlockId.Cattail,
            BlockId.Plate,
            BlockId.BlackDragonflyJar,
            BlockId.BlueDragonflyJar,
            BlockId.GreenDragonflyJar,
            BlockId.OrangeDragonflyJar,
            BlockId.RedDragonflyJar,
            BlockId.YellowDragonflyJar,
            BlockId.GoldDragonflyJar,
            BlockId.SeaOats,
            BlockId.OasisPlants,
            BlockId.BoulderStatue,
            BlockId.MaggotCage,
            BlockId.RatCage,
            BlockId.LadybugCage,
            BlockId.OwlCage,
            BlockId.PupfishBowl,
            BlockId.GoldLadybugCage,
            BlockId.LawnFlamingo,
            BlockId.PottedPlants,
            BlockId.PottedPlants2,
            BlockId.Seaweed,
            BlockId.TurtleCage,
            BlockId.JungleTurtleCage,
            BlockId.Sandcastles,
            BlockId.GrebeCage,
            BlockId.SeagullCage,
            BlockId.WaterStriderCage,
            BlockId.GoldWaterStriderCage,
            BlockId.SeahorseCage,
            BlockId.GoldSeahorseCage,
            BlockId.GolfTrophies,
            BlockId.PlasmaLamp,
            BlockId.FogMachine,
            BlockId.GardenGnome,
            BlockId.PinkFairyJar,
            BlockId.GreenFairyJar,
            BlockId.BlueFairyJar,
            BlockId.BambooPlant,
            BlockId.SoulInABottles,
            BlockId.TatteredWoodSign,
            BlockId.RockGolemHead,
            BlockId.HellButterflyJar,
            BlockId.LavaflyInABottle,
            BlockId.MagmaSnailCage,
            BlockId.TopazTree,
            BlockId.AmethystTree,
            BlockId.SapphireTree,
            BlockId.EmeraldTree,
            BlockId.RubyTree,
            BlockId.DiamondTree,
            BlockId.AmberTree,
            BlockId.GemSaplings,
            BlockId.HangingPots,
            BlockId.HangingBrazier,
            BlockId.MiniVolcano,
            BlockId.LargeVolcano,
            BlockId.SakuraSapling,
            BlockId.SakuraTree,
            BlockId.TeleportationPylons,
            BlockId.LavaSerpentBowl,
            BlockId.AmethystBunnyCage,
            BlockId.TopazBunnyCage,
            BlockId.SapphireBunnyCage,
            BlockId.EmeraldBunnyCage,
            BlockId.RubyBunnyCage,
            BlockId.DiamondBunnyCage,
            BlockId.AmberBunnyCage,
            BlockId.AmethystSquirrelCage,
            BlockId.TopazSquirrelCage,
            BlockId.SapphireSquirrelCage,
            BlockId.EmeraldSquirrelCage,
            BlockId.RubySquirrelCage,
            BlockId.DiamondSquirrelCage,
            BlockId.AmberSquirrelCage,
            BlockId.PottedLavaPlants,
            BlockId.PottedEmberTendrils,
            BlockId.YellowWillowSapling,
            BlockId.YellowWillowTree,
            BlockId.BossRelics,
            BlockId.TruffleWormCage,
            BlockId.PrismaticLacewingJar,
            BlockId.SliceOfCake,
            BlockId.Teapot
        };

        /// <summary>
        /// Returns a value indicating whether the block <paramref name="id"/> has frames.
        /// </summary>
        /// <param name="id">The block ID.</param>
        /// <returns>
        /// <see langword="true"/> if the block <paramref name="id"/> has frames; otherwise, <see langword="false"/>.
        /// </returns>
        [Pure]
        public static bool HasFrames(this BlockId id) => _frames.Contains(id);
    }
}
